import type { BankThread } from './types'

// AUTO-GENERATED curriculum spine (P2). Every concept has exactly one home
// thread, grouped by era into sections (the `unit` field) and ordered
// chronologically. Tiers come from graph centrality (edge in-degree):
// tier 1 = anchors, tier 2 = supporting, tier 3 = detail. To regenerate,
// restore src/content/_gen.test.ts and run it.

export const THREADS: BankThread[] = [
  {
    id: "first-civilisations",
    name: "The first civilisations",
    description:
      "Mesopotamia, Egypt, the Indus, and early China. The first cities, writing, and law, and the roots of Hinduism and Judaism.",
    displayOrder: 1,
    unit: "The Ancient World",
    members: [
      { concept: "mesopotamia", tier: 1 },
      { concept: "great-pyramid-giza", tier: 3 },
      { concept: "ancient-egypt", tier: 2 },
      { concept: "indus-valley", tier: 3 },
      { concept: "code-of-hammurabi", tier: 2 },
      { concept: "hinduism-core", tier: 2 },
      { concept: "judaism-core", tier: 1 },
      { concept: "trojan-war", tier: 3 },
      { concept: "phoenicia", tier: 3 },
      { concept: "ancient-israel", tier: 3 },
      { concept: "ancient-china", tier: 2 },
      { concept: "vedic-period", tier: 2 },
    ],
  },
  {
    id: "ancient-empires-faiths",
    name: "Ancient empires and the first faiths",
    description:
      "Assyria, Babylon, and the vast Persian empire, alongside the early Greek world and the birth of Zoroastrianism and Buddhism.",
    displayOrder: 2,
    unit: "The Ancient World",
    members: [
      { concept: "hebrew-bible", tier: 2 },
      { concept: "olympic-games", tier: 3 },
      { concept: "romulus-remus", tier: 3 },
      { concept: "homer", tier: 3 },
      { concept: "assyrian-empire", tier: 2 },
      { concept: "greek-city-states", tier: 1 },
      { concept: "neo-babylonian-empire", tier: 2 },
      { concept: "zoroastrianism", tier: 3 },
      { concept: "babylon-city", tier: 3 },
      { concept: "cyrus-the-great", tier: 2 },
      { concept: "persian-empire", tier: 1 },
      { concept: "darius-i", tier: 2 },
      { concept: "achaemenid-satrapy", tier: 2 },
      { concept: "buddhism-core", tier: 2 },
    ],
  },
  {
    id: "greece-persian-wars",
    name: "Greece and the Persian Wars",
    description:
      "Athenian democracy, Sparta, and the Greek cities holding off the Persian empire at Marathon, Thermopylae, and Salamis.",
    displayOrder: 3,
    unit: "The Ancient World",
    members: [
      { concept: "roman-republic", tier: 1 },
      { concept: "athenian-democracy", tier: 1 },
      { concept: "sparta", tier: 2 },
      { concept: "confucius", tier: 2 },
      { concept: "battle-of-marathon", tier: 2 },
      { concept: "xerxes-i", tier: 2 },
      { concept: "battle-of-thermopylae", tier: 1 },
      { concept: "battle-of-salamis", tier: 2 },
      { concept: "pericles", tier: 2 },
      { concept: "roman-law", tier: 2 },
      { concept: "herodotus", tier: 3 },
      { concept: "the-parthenon", tier: 3 },
      { concept: "peloponnesian-war", tier: 2 },
      { concept: "thucydides", tier: 2 },
      { concept: "taoism", tier: 3 },
    ],
  },
  {
    id: "philosophy-and-alexander",
    name: "Philosophy and Alexander",
    description:
      "Socrates, Plato, and Aristotle, then Alexander the Great carrying Greek culture from Egypt to India.",
    displayOrder: 4,
    unit: "The Ancient World",
    members: [
      { concept: "socrates", tier: 2 },
      { concept: "plato", tier: 3 },
      { concept: "philip-ii-macedon", tier: 3 },
      { concept: "aristotle", tier: 2 },
      { concept: "alexander-the-great", tier: 1 },
      { concept: "seleucid-empire", tier: 3 },
      { concept: "ptolemaic-egypt", tier: 2 },
      { concept: "euclid", tier: 2 },
      { concept: "hellenism", tier: 3 },
      { concept: "roman-senate", tier: 2 },
      { concept: "spread-of-greek-language", tier: 2 },
      { concept: "library-of-alexandria", tier: 2 },
      { concept: "ashoka", tier: 3 },
    ],
  },
  {
    id: "rome-conquers-mediterranean",
    name: "Rome conquers the Mediterranean",
    description:
      "The Punic Wars against Carthage, the rise of the Roman Republic, and the civil wars that ended it with Caesar.",
    displayOrder: 5,
    unit: "The Ancient World",
    members: [
      { concept: "punic-wars", tier: 2 },
      { concept: "carthage", tier: 2 },
      { concept: "archimedes", tier: 3 },
      { concept: "buddhist-spread", tier: 2 },
      { concept: "roman-provinces", tier: 3 },
      { concept: "qin-dynasty", tier: 2 },
      { concept: "great-wall-of-china", tier: 3 },
      { concept: "hannibal", tier: 2 },
      { concept: "scipio-africanus", tier: 2 },
      { concept: "han-dynasty", tier: 2 },
      { concept: "gracchi", tier: 3 },
      { concept: "gracchi-brothers", tier: 3 },
      { concept: "silk-road", tier: 2 },
      { concept: "roman-army", tier: 3 },
      { concept: "spartacus-revolt", tier: 3 },
      { concept: "cicero", tier: 3 },
      { concept: "first-triumvirate", tier: 2 },
      { concept: "cleopatra-vii", tier: 1 },
      { concept: "battle-of-pharsalus", tier: 3 },
      { concept: "cleopatra-and-caesar", tier: 2 },
    ],
  },
  {
    id: "the-roman-empire",
    name: "The Roman Empire",
    description:
      "Augustus to the Antonines. The empire at its height, the Pax Romana, and the new faith spreading through its cities.",
    displayOrder: 6,
    unit: "The Ancient World",
    members: [
      { concept: "julius-caesar", tier: 1 },
      { concept: "assassination-of-caesar", tier: 3 },
      { concept: "second-triumvirate", tier: 2 },
      { concept: "mark-antony", tier: 2 },
      { concept: "battle-of-actium", tier: 2 },
      { concept: "augustus-caesar", tier: 1 },
      { concept: "pax-romana", tier: 2 },
      { concept: "virgil-aeneid", tier: 3 },
      { concept: "roman-religion", tier: 3 },
      { concept: "christianity-core", tier: 1 },
      { concept: "st-paul", tier: 2 },
      { concept: "nero-emperor", tier: 2 },
      { concept: "roman-persecution-christians", tier: 2 },
      { concept: "vespasian-emperor", tier: 2 },
      { concept: "flavian-dynasty", tier: 3 },
      { concept: "year-of-four-emperors", tier: 3 },
      { concept: "new-testament", tier: 2 },
      { concept: "pompeii", tier: 3 },
      { concept: "colosseum", tier: 2 },
      { concept: "trajan-emperor", tier: 3 },
      { concept: "roman-engineering", tier: 2 },
      { concept: "roman-gladiators", tier: 3 },
      { concept: "roman-empire", tier: 1 },
      { concept: "hadrian-emperor", tier: 2 },
      { concept: "pantheon-rome", tier: 3 },
      { concept: "marcus-aurelius", tier: 2 },
      { concept: "antonine-plague", tier: 3 },
    ],
  },
  {
    id: "fall-of-rome",
    name: "The fall of Rome",
    description:
      "Crisis, Constantine and a Christian empire, then the slow collapse of the Roman west under pressure from outside.",
    displayOrder: 7,
    unit: "The Ancient World",
    members: [
      { concept: "roman-citizenship", tier: 3 },
      { concept: "origen-theologian", tier: 3 },
      { concept: "sassanid-empire", tier: 3 },
      { concept: "third-century-crisis", tier: 2 },
      { concept: "diocletian-emperor", tier: 2 },
      { concept: "tetrarchy", tier: 3 },
      { concept: "lactantius", tier: 3 },
      { concept: "constantine-i", tier: 1 },
      { concept: "edict-of-milan", tier: 2 },
      { concept: "council-of-nicaea", tier: 2 },
      { concept: "nicene-creed", tier: 3 },
      { concept: "founding-of-constantinople", tier: 3 },
      { concept: "julian-the-apostate", tier: 3 },
      { concept: "theodosius-i", tier: 2 },
      { concept: "st-jerome-vulgate", tier: 3 },
      { concept: "split-roman-empire", tier: 3 },
      { concept: "alaric-visigoth", tier: 3 },
      { concept: "st-augustine", tier: 3 },
      { concept: "visigoths-sack-rome", tier: 2 },
      { concept: "attila-the-hun", tier: 3 },
      { concept: "vandals-sack-rome", tier: 3 },
      { concept: "odoacer", tier: 3 },
      { concept: "boethius", tier: 3 },
    ],
  },
  {
    id: "byzantium-and-islam",
    name: "After Rome: Byzantium and Islam",
    description:
      "Justinian's eastern empire, the Hagia Sophia, and the explosive rise and spread of Islam across three continents.",
    displayOrder: 8,
    unit: "The Medieval World",
    members: [
      { concept: "fall-of-western-rome", tier: 1 },
      { concept: "silk-road-byzantium", tier: 3 },
      { concept: "justinian-i", tier: 1 },
      { concept: "justinian-code", tier: 2 },
      { concept: "early-monasticism", tier: 3 },
      { concept: "hagia-sophia", tier: 3 },
      { concept: "byzantine-art-mosaics", tier: 3 },
      { concept: "plague-of-justinian", tier: 3 },
      { concept: "byzantine-empire", tier: 1 },
      { concept: "islam-core", tier: 1 },
      { concept: "muhammad-life-hijra", tier: 3 },
      { concept: "rashidun-caliphate", tier: 2 },
      { concept: "umayyad-caliphate", tier: 2 },
      { concept: "greek-fire", tier: 3 },
      { concept: "byzantine-iconoclasm", tier: 3 },
      { concept: "battle-of-tours", tier: 3 },
    ],
  },
  {
    id: "early-medieval-west",
    name: "Charlemagne and the Islamic golden age",
    description:
      "Vikings, Charlemagne's revived empire, feudal Europe, and the scholars of the Abbasid Baghdad golden age.",
    displayOrder: 9,
    unit: "The Medieval World",
    members: [
      { concept: "abbasid-caliphate", tier: 2 },
      { concept: "viking-age", tier: 2 },
      { concept: "charlemagne", tier: 2 },
      { concept: "trans-saharan-trade", tier: 3 },
      { concept: "al-khwarizmi", tier: 3 },
      { concept: "rus-origin", tier: 2 },
      { concept: "cyril-methodius", tier: 3 },
      { concept: "great-moravia", tier: 2 },
      { concept: "islamic-golden-age", tier: 1 },
      { concept: "feudalism", tier: 1 },
      { concept: "normandy-founding", tier: 2 },
      { concept: "holy-roman-empire", tier: 2 },
      { concept: "varangian-guard", tier: 2 },
    ],
  },
  {
    id: "high-middle-ages",
    name: "The high middle ages",
    description:
      "The Norman conquest, the first universities, Gothic cathedrals, and the Crusades opening Europe to the wider world.",
    displayOrder: 10,
    unit: "The Medieval World",
    members: [
      { concept: "kingdom-of-hungary", tier: 2 },
      { concept: "leif-eriksson-vinland", tier: 3 },
      { concept: "ibn-sina-avicenna", tier: 3 },
      { concept: "norman-conquest", tier: 2 },
      { concept: "william-conqueror", tier: 2 },
      { concept: "battle-of-manzikert", tier: 3 },
      { concept: "papal-investiture", tier: 2 },
      { concept: "domesday-book", tier: 2 },
      { concept: "medieval-universities", tier: 2 },
      { concept: "alexios-komnenos", tier: 2 },
      { concept: "crusades-overview", tier: 1 },
      { concept: "first-crusade", tier: 2 },
      { concept: "scholasticism", tier: 2 },
      { concept: "medieval-manuscript-culture", tier: 3 },
      { concept: "gothic-architecture", tier: 3 },
      { concept: "frederick-barbarossa", tier: 3 },
      { concept: "notre-dame-de-paris", tier: 3 },
      { concept: "ibn-rushd-averroes", tier: 2 },
      { concept: "saladin", tier: 2 },
      { concept: "teutonic-knights", tier: 3 },
      { concept: "richard-i-third-crusade", tier: 3 },
    ],
  },
  {
    id: "mongols-and-scholastics",
    name: "Mongols, scholastics, and trade",
    description:
      "Genghis Khan s empire, the Magna Carta, Thomas Aquinas, and the long trade roads linking China to the Mediterranean.",
    displayOrder: 11,
    unit: "The Medieval World",
    members: [
      { concept: "pope-innocent-iii", tier: 3 },
      { concept: "genghis-khan", tier: 1 },
      { concept: "childrens-crusade", tier: 3 },
      { concept: "magna-carta", tier: 2 },
      { concept: "mongol-conquest-of-china", tier: 3 },
      { concept: "il-khanate", tier: 3 },
      { concept: "mongol-sack-of-baghdad", tier: 2 },
      { concept: "kublai-khan", tier: 2 },
      { concept: "pax-mongolica", tier: 2 },
      { concept: "thomas-aquinas", tier: 2 },
      { concept: "marco-polo", tier: 2 },
      { concept: "ottoman-rise", tier: 3 },
      { concept: "dante-alighieri", tier: 3 },
      { concept: "mansa-musa-mali", tier: 3 },
    ],
  },
  {
    id: "late-medieval-crisis",
    name: "Plague and the late medieval crisis",
    description:
      "The Black Death, the Hundred Years War, the fall of Constantinople, and the end of the medieval order.",
    displayOrder: 12,
    unit: "The Medieval World",
    members: [
      { concept: "hundred-years-war", tier: 2 },
      { concept: "black-death", tier: 1 },
      { concept: "black-death-social-impact", tier: 3 },
      { concept: "geoffrey-chaucer", tier: 3 },
      { concept: "joan-of-arc", tier: 3 },
      { concept: "fall-of-constantinople", tier: 3 },
      { concept: "ottoman-empire", tier: 3 },
      { concept: "wars-of-the-roses", tier: 3 },
    ],
  },
  {
    id: "the-renaissance",
    name: "The Renaissance",
    description:
      "Florence, humanism, the printing press, and the first European voyages that reached the Americas.",
    displayOrder: 13,
    unit: "Renaissance and Reformation",
    members: [
      { concept: "humanism", tier: 2 },
      { concept: "perspective-in-art", tier: 3 },
      { concept: "aztec-empire", tier: 3 },
      { concept: "brunelleschi-dome", tier: 3 },
      { concept: "printing-press", tier: 2 },
      { concept: "the-renaissance", tier: 1 },
      { concept: "medici-family", tier: 2 },
      { concept: "inca-empire", tier: 3 },
      { concept: "spanish-inquisition", tier: 3 },
      { concept: "botticelli", tier: 3 },
      { concept: "age-of-exploration", tier: 2 },
      { concept: "christopher-columbus", tier: 3 },
    ],
  },
  {
    id: "reformation-new-world",
    name: "Reformation and the new world",
    description:
      "Luther splits the Church, the great artists work in Rome, and Spain conquers the Aztec and Inca empires.",
    displayOrder: 14,
    unit: "Renaissance and Reformation",
    members: [
      { concept: "leonardo-da-vinci", tier: 2 },
      { concept: "columbian-exchange", tier: 2 },
      { concept: "raphael", tier: 3 },
      { concept: "erasmus", tier: 3 },
      { concept: "michelangelo", tier: 3 },
      { concept: "machiavelli", tier: 3 },
      { concept: "thomas-more", tier: 3 },
      { concept: "protestant-reformation", tier: 1 },
      { concept: "martin-luther", tier: 3 },
      { concept: "suleiman-magnificent", tier: 3 },
      { concept: "hernan-cortes", tier: 3 },
      { concept: "habsburg-monarchy", tier: 2 },
      { concept: "francisco-pizarro", tier: 3 },
      { concept: "henry-viii", tier: 2 },
      { concept: "john-calvin", tier: 3 },
      { concept: "jesuits", tier: 3 },
      { concept: "copernicus", tier: 2 },
      { concept: "council-of-trent", tier: 2 },
    ],
  },
  {
    id: "wars-of-religion",
    name: "The wars of religion",
    description:
      "Elizabethan England, the Armada, the Thirty Years War, and the first stirrings of modern science with Galileo and Descartes.",
    displayOrder: 15,
    unit: "Renaissance and Reformation",
    members: [
      { concept: "elizabeth-i", tier: 3 },
      { concept: "spanish-armada", tier: 3 },
      { concept: "atlantic-slave-trade", tier: 3 },
      { concept: "galileo", tier: 3 },
      { concept: "thirty-years-war", tier: 1 },
      { concept: "francis-bacon", tier: 3 },
      { concept: "rene-descartes", tier: 3 },
      { concept: "peace-of-westphalia", tier: 3 },
      { concept: "dutch-golden-age", tier: 3 },
    ],
  },
  {
    id: "scientific-revolution-enlightenment",
    name: "The scientific revolution and the Enlightenment",
    description:
      "Newton s universe and the Enlightenment idea that reason, not tradition, should order society and government.",
    displayOrder: 16,
    unit: "Renaissance and Reformation",
    members: [
      { concept: "scientific-revolution", tier: 1 },
      { concept: "isaac-newton", tier: 2 },
      { concept: "enlightenment", tier: 1 },
      { concept: "first-past-the-post", tier: 3 },
      { concept: "separation-of-powers", tier: 2 },
      { concept: "american-revolution", tier: 2 },
    ],
  },
  {
    id: "age-of-revolutions",
    name: "The age of revolutions",
    description:
      "The French and Industrial Revolutions and Napoleon, the twin upheavals that built the modern world.",
    displayOrder: 17,
    unit: "Revolutions and the 19th Century",
    members: [
      { concept: "steam-engine", tier: 2 },
      { concept: "textile-mills", tier: 2 },
      { concept: "french-revolution", tier: 1 },
      { concept: "parliamentary-vs-presidential", tier: 2 },
      { concept: "utilitarianism", tier: 3 },
      { concept: "cotton-gin", tier: 3 },
      { concept: "industrial-revolution", tier: 1 },
      { concept: "romanticism", tier: 2 },
      { concept: "napoleon", tier: 2 },
      { concept: "haitian-revolution", tier: 3 },
      { concept: "luddites", tier: 2 },
      { concept: "congress-of-vienna", tier: 3 },
      { concept: "latin-american-independence", tier: 3 },
    ],
  },
  {
    id: "restoration-and-industry",
    name: "Restoration Europe and early industry",
    description:
      "The settlement after Napoleon, the spread of railways and factories, and the hard early years of the industrial age.",
    displayOrder: 18,
    unit: "Revolutions and the 19th Century",
    members: [
      { concept: "uk-government-structure", tier: 1 },
      { concept: "uk-constituents", tier: 3 },
      { concept: "ottoman-empire-context", tier: 2 },
      { concept: "metternich-concert", tier: 2 },
      { concept: "socialism-early", tier: 2 },
      { concept: "greek-independence", tier: 2 },
      { concept: "railways-locomotive", tier: 2 },
      { concept: "decembrist-revolt", tier: 3 },
      { concept: "romantic-nationalism", tier: 2 },
      { concept: "child-labour", tier: 2 },
      { concept: "chartism", tier: 2 },
      { concept: "photography", tier: 3 },
    ],
  },
  {
    id: "age-of-ideologies",
    name: "1848 and the age of ideologies",
    description:
      "The revolutions of 1848, Marx and socialism, Darwin, and the new industrial Britain and its empire.",
    displayOrder: 19,
    unit: "Revolutions and the 19th Century",
    members: [
      { concept: "anarchism", tier: 3 },
      { concept: "opium-wars", tier: 2 },
      { concept: "ludovit-stur", tier: 3 },
      { concept: "telegraph", tier: 3 },
      { concept: "irish-famine", tier: 3 },
      { concept: "anaesthesia", tier: 3 },
      { concept: "karl-marx", tier: 1 },
      { concept: "revolutions-1848", tier: 1 },
      { concept: "womens-suffrage", tier: 2 },
      { concept: "urbanisation", tier: 2 },
      { concept: "thermodynamics", tier: 3 },
      { concept: "realism-literature", tier: 3 },
      { concept: "crimean-war", tier: 3 },
      { concept: "british-india", tier: 2 },
      { concept: "charles-darwin", tier: 3 },
      { concept: "american-civil-war", tier: 2 },
      { concept: "italian-risorgimento", tier: 2 },
    ],
  },
  {
    id: "nations-and-empires",
    name: "Nations, empires, and science",
    description:
      "The unification of Germany and Italy, the scramble for Africa, and a wave of scientific and artistic breakthroughs.",
    displayOrder: 20,
    unit: "Revolutions and the 19th Century",
    members: [
      { concept: "abolition-of-slavery", tier: 1 },
      { concept: "germ-theory", tier: 2 },
      { concept: "electromagnetism-faraday", tier: 3 },
      { concept: "austria-hungary", tier: 2 },
      { concept: "trade-unions", tier: 2 },
      { concept: "meiji-restoration", tier: 3 },
      { concept: "periodic-table", tier: 3 },
      { concept: "suez-canal", tier: 3 },
      { concept: "social-darwinism", tier: 3 },
      { concept: "unification-of-germany", tier: 2 },
      { concept: "paris-commune", tier: 3 },
      { concept: "impressionism", tier: 3 },
      { concept: "telephone-bell", tier: 2 },
      { concept: "antisemitism-modern", tier: 3 },
      { concept: "nietzsche", tier: 3 },
      { concept: "scramble-for-africa", tier: 2 },
      { concept: "nikola-tesla", tier: 2 },
    ],
  },
  {
    id: "road-to-war",
    name: "The road to war",
    description:
      "Einstein and Freud, the naval arms race, and the tangle of alliances that pulled Europe toward 1914.",
    displayOrder: 21,
    unit: "Revolutions and the 19th Century",
    members: [
      { concept: "xray-rontgen", tier: 3 },
      { concept: "western-canon", tier: 3 },
      { concept: "boxer-rebellion", tier: 3 },
      { concept: "sigmund-freud", tier: 3 },
      { concept: "marie-curie", tier: 2 },
      { concept: "dreadnought-race", tier: 3 },
      { concept: "triple-alliance-entente", tier: 2 },
      { concept: "balkan-wars", tier: 2 },
      { concept: "archduke-franz-ferdinand", tier: 3 },
      { concept: "albert-einstein", tier: 1 },
    ],
  },
  {
    id: "first-world-war",
    name: "The First World War",
    description:
      "The trenches of the Western Front, a global war of empires, and the Russian Revolution it set off.",
    displayOrder: 22,
    unit: "The World Wars",
    members: [
      { concept: "wwi-trigger", tier: 1 },
      { concept: "western-front-trenches", tier: 2 },
      { concept: "battle-of-gallipoli", tier: 3 },
      { concept: "armenian-genocide", tier: 3 },
      { concept: "battle-of-the-somme", tier: 2 },
      { concept: "battle-of-verdun", tier: 3 },
      { concept: "lawrence-of-arabia", tier: 3 },
      { concept: "russian-revolution", tier: 1 },
      { concept: "u-boat-warfare", tier: 2 },
      { concept: "zimmermann-telegram", tier: 2 },
      { concept: "us-entry-wwi", tier: 2 },
      { concept: "balfour-declaration", tier: 3 },
      { concept: "february-revolution-1917", tier: 3 },
      { concept: "october-revolution-1917", tier: 2 },
      { concept: "bolsheviks-lenin", tier: 2 },
      { concept: "trotsky", tier: 3 },
    ],
  },
  {
    id: "troubled-peace",
    name: "Revolution and the troubled peace",
    description:
      "Versailles, the new Soviet state, the rise of fascism in Italy, and the crash that became the Great Depression.",
    displayOrder: 23,
    unit: "The World Wars",
    members: [
      { concept: "czechoslovakia-1918", tier: 2 },
      { concept: "spanish-flu", tier: 3 },
      { concept: "armistice-1918", tier: 3 },
      { concept: "russian-civil-war", tier: 2 },
      { concept: "cheka-red-terror", tier: 2 },
      { concept: "treaty-of-versailles", tier: 1 },
      { concept: "weimar-republic", tier: 2 },
      { concept: "formation-of-ussr", tier: 2 },
      { concept: "mussolini-italian-fascism", tier: 2 },
      { concept: "march-on-rome", tier: 3 },
      { concept: "hyperinflation-germany-1923", tier: 3 },
      { concept: "great-depression", tier: 3 },
      { concept: "wall-street-crash-1929", tier: 3 },
    ],
  },
  {
    id: "rise-of-dictators",
    name: "The rise of the dictators",
    description:
      "Hitler and Stalin, the terror and famine of the 1930s, and the failure of appeasement to stop another war.",
    displayOrder: 24,
    unit: "The World Wars",
    members: [
      { concept: "stalins-collectivisation", tier: 2 },
      { concept: "soviet-gulags", tier: 2 },
      { concept: "japanese-empire-manchuria", tier: 2 },
      { concept: "rise-of-hitler", tier: 1 },
      { concept: "holodomor", tier: 2 },
      { concept: "night-of-long-knives", tier: 3 },
      { concept: "nuremberg-laws", tier: 2 },
      { concept: "league-of-nations-failure", tier: 3 },
      { concept: "franco-spanish-civil-war", tier: 2 },
      { concept: "guernica", tier: 3 },
      { concept: "nanking-massacre", tier: 3 },
      { concept: "kristallnacht", tier: 3 },
      { concept: "appeasement-munich", tier: 3 },
    ],
  },
  {
    id: "second-world-war",
    name: "The Second World War and the Holocaust",
    description:
      "The deadliest war in history, the Holocaust, and the first use of nuclear weapons to end it.",
    displayOrder: 25,
    unit: "The World Wars",
    members: [
      { concept: "world-war-two", tier: 1 },
      { concept: "molotov-ribbentrop-pact", tier: 2 },
      { concept: "blitzkrieg", tier: 3 },
      { concept: "fall-of-france", tier: 2 },
      { concept: "dunkirk-evacuation", tier: 2 },
      { concept: "battle-of-britain", tier: 2 },
      { concept: "operation-barbarossa", tier: 2 },
      { concept: "siege-of-leningrad", tier: 2 },
      { concept: "pearl-harbour", tier: 2 },
      { concept: "einsatzgruppen", tier: 3 },
      { concept: "the-holocaust", tier: 1 },
      { concept: "battle-of-stalingrad", tier: 2 },
      { concept: "wannsee-conference", tier: 2 },
      { concept: "auschwitz-birkenau", tier: 2 },
      { concept: "righteous-among-nations", tier: 3 },
      { concept: "pacific-island-hopping", tier: 3 },
      { concept: "slovak-national-uprising", tier: 3 },
      { concept: "d-day-normandy", tier: 3 },
      { concept: "liberation-of-paris", tier: 3 },
      { concept: "anne-frank", tier: 3 },
      { concept: "nuclear-weapons", tier: 2 },
      { concept: "hiroshima-atomic-bomb", tier: 2 },
      { concept: "nagasaki-atomic-bomb", tier: 3 },
      { concept: "nuremberg-trials", tier: 3 },
      { concept: "firebombing-of-dresden", tier: 3 },
    ],
  },
  {
    id: "world-divided",
    name: "A world divided",
    description:
      "The United Nations, the partition of India, the Marshall Plan, and the Iron Curtain falling across Europe.",
    displayOrder: 26,
    unit: "The Cold War and After",
    members: [
      { concept: "gandhi-political", tier: 3 },
      { concept: "united-nations", tier: 1 },
      { concept: "truman-doctrine", tier: 3 },
      { concept: "indian-independence-partition", tier: 2 },
      { concept: "jawaharlal-nehru", tier: 3 },
      { concept: "pakistani-founding", tier: 3 },
      { concept: "marshall-plan", tier: 3 },
      { concept: "berlin-airlift", tier: 3 },
      { concept: "nato-founding", tier: 3 },
      { concept: "korean-war", tier: 3 },
      { concept: "mccarthyism", tier: 3 },
      { concept: "mau-mau-uprising", tier: 3 },
    ],
  },
  {
    id: "nuclear-age-decolonisation",
    name: "The nuclear age and decolonisation",
    description:
      "The space race, the Cuban Missile Crisis, and dozens of new nations emerging as the European empires dissolved.",
    displayOrder: 27,
    unit: "The Cold War and After",
    members: [
      { concept: "korean-peninsula", tier: 2 },
      { concept: "ho-chi-minh-vietnamese-independence", tier: 3 },
      { concept: "warsaw-pact", tier: 2 },
      { concept: "suez-crisis", tier: 3 },
      { concept: "hungarian-revolution-1956", tier: 3 },
      { concept: "european-union", tier: 2 },
      { concept: "sputnik", tier: 3 },
      { concept: "algerian-war", tier: 3 },
      { concept: "cold-war", tier: 1 },
      { concept: "decolonisation", tier: 1 },
      { concept: "patrice-lumumba-congo", tier: 3 },
      { concept: "space-race", tier: 1 },
      { concept: "television-mass-medium", tier: 3 },
      { concept: "yuri-gagarin", tier: 3 },
      { concept: "alan-shepard", tier: 3 },
    ],
  },
  {
    id: "sixties-rights-and-revolt",
    name: "The Sixties: rights and revolt",
    description:
      "Civil rights, the Vietnam War, the Prague Spring, the counterculture, and the first humans on the Moon.",
    displayOrder: 28,
    unit: "The Cold War and After",
    members: [
      { concept: "cuban-missile-crisis", tier: 3 },
      { concept: "second-wave-feminism", tier: 3 },
      { concept: "martin-luther-king", tier: 3 },
      { concept: "malcolm-x", tier: 2 },
      { concept: "civil-rights-movement", tier: 1 },
      { concept: "rock-music-beatles", tier: 3 },
      { concept: "gulf-of-tonkin", tier: 3 },
      { concept: "black-power-movement", tier: 3 },
      { concept: "counterculture", tier: 3 },
      { concept: "six-day-war", tier: 2 },
      { concept: "prague-spring", tier: 3 },
      { concept: "anti-vietnam-protests", tier: 2 },
      { concept: "student-movements-1968", tier: 2 },
      { concept: "vietnam-war", tier: 1 },
      { concept: "tet-offensive", tier: 3 },
      { concept: "my-lai-massacre", tier: 3 },
      { concept: "prague-spring-1968", tier: 3 },
    ],
  },
  {
    id: "detente-to-the-wall",
    name: "Detente to the fall of the Wall",
    description:
      "Oil shocks, the end of detente, Solidarity and Gorbachev, and the sudden collapse of communism in 1989.",
    displayOrder: 29,
    unit: "The Cold War and After",
    members: [
      { concept: "moon-landing", tier: 2 },
      { concept: "apollo-programme", tier: 3 },
      { concept: "nixon-china", tier: 3 },
      { concept: "salt-treaties", tier: 3 },
      { concept: "hip-hop", tier: 3 },
      { concept: "yom-kippur-war", tier: 2 },
      { concept: "opec-oil-crisis", tier: 3 },
      { concept: "chilean-coup-pinochet", tier: 3 },
      { concept: "helsinki-accords", tier: 3 },
      { concept: "cambodian-genocide", tier: 3 },
      { concept: "nicaraguan-revolution", tier: 3 },
      { concept: "soviet-invasion-afghanistan", tier: 3 },
      { concept: "iranian-revolution", tier: 3 },
      { concept: "iran-hostage-crisis", tier: 3 },
      { concept: "solidarity-poland", tier: 3 },
      { concept: "challenger-disaster", tier: 3 },
      { concept: "gorbachev-glasnost-perestroika", tier: 2 },
      { concept: "chernobyl-disaster", tier: 3 },
      { concept: "fall-of-berlin-wall", tier: 1 },
      { concept: "velvet-revolution", tier: 1 },
      { concept: "tiananmen-square-1989", tier: 3 },
      { concept: "nelson-mandela-apartheid", tier: 3 },
    ],
  },
  {
    id: "after-the-cold-war",
    name: "After the Cold War",
    description:
      "The Soviet collapse, the World Wide Web, the wars in the Gulf and the Balkans, and a Europe reuniting around the EU.",
    displayOrder: 30,
    unit: "The Cold War and After",
    members: [
      { concept: "fall-of-soviet-union", tier: 1 },
      { concept: "world-wide-web", tier: 2 },
      { concept: "gulf-war-1991", tier: 3 },
      { concept: "slovakia-neighbours", tier: 3 },
      { concept: "oslo-accords", tier: 3 },
      { concept: "rwandan-genocide", tier: 3 },
      { concept: "bosnian-war-srebrenica", tier: 3 },
      { concept: "september-11", tier: 3 },
      { concept: "eu-member-states", tier: 2 },
    ],
  },
  {
    id: "the-present-century",
    name: "The present century",
    description:
      "The smartphone, the 2008 crash, the Arab Spring, and the slow emergence of climate change.",
    displayOrder: 31,
    unit: "The Cold War and After",
    members: [
      { concept: "smartphone", tier: 1 },
      { concept: "2008-financial-crisis", tier: 3 },
      { concept: "arab-spring", tier: 3 },
      { concept: "climate-change", tier: 3 },
      { concept: "sahel", tier: 3 },
    ],
  },
]
