import type { BankConcept } from '../types'

export const CLASSICAL_EXPANDED: BankConcept[] = [
  // â”€â”€ Roman Empire: Augustus to Fall â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'augustus-caesar',
    name: 'Augustus Caesar',
    domain: 'history',
    approxYear: -27,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Rome's first emperor, born Gaius Octavius, transformed the Republic into an empire after defeating Mark Antony and Cleopatra at the Battle of Actium in 31 BCE. He ruled for 44 years under the title Augustus, meaning \"the revered one\", and his reign opened the Pax Romana â€” two centuries of relative peace across the Mediterranean. Every subsequent Roman emperor modelled his rule on Augustus.",
    wikipedia: 'https://en.wikipedia.org/wiki/Augustus',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Augustus defeated Mark Antony at the Battle of ____ in 31 BCE.', answer: 'Actium' },
      { format: 'contrast', prompt: "What title did Rome's first emperor adopt, meaning \"the revered one\"?", answer: 'Augustus', distractors: ['Caesar', 'Pontifex Maximus', 'Princeps'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'successor_of' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'pax-romana', relation: 'caused' },
      { to: 'battle-of-actium', relation: 'caused' },
      { to: 'mark-antony', relation: 'opposed' },
    ],
  },
  {
    id: 'pax-romana',
    name: 'Pax Romana',
    domain: 'history',
    approxYear: -27,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'A roughly 200-year period of relative peace and stability across the Roman Empire, beginning with the reign of Augustus in 27 BCE and lasting until 180 CE. Trade flourished, roads connected Britain to Mesopotamia, and the empire\'s population reached around 70 million. The phrase means "Roman Peace" and remains a shorthand for any era of imperial stability.',
    wikipedia: 'https://en.wikipedia.org/wiki/Pax_Romana',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Pax Romana began with the reign of ____ in 27 BCE.', answer: 'Augustus' },
      { format: 'contrast', prompt: 'How long did the Pax Romana roughly last?', answer: '200 years', distractors: ['50 years', '400 years', '100 years'] },
    ],
    edges: [
      { to: 'augustus-caesar', relation: 'influenced_by' },
      { to: 'roman-empire', relation: 'part_of' },
    ],
  },
  {
    id: 'hadrian-emperor',
    name: 'Hadrian',
    domain: 'history',
    approxYear: 117,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Roman emperor from 117 to 138 CE, Hadrian is famous for consolidating the empire's borders rather than expanding them, most visibly by ordering the construction of Hadrian's Wall across northern Britain. An ardent admirer of Greek culture, he rebuilt the Pantheon in Rome and completed the Temple of Olympian Zeus in Athens. His reign is considered one of the \"Five Good Emperors\" period.",
    wikipedia: 'https://en.wikipedia.org/wiki/Hadrian',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Hadrian ordered the construction of ____ Wall across northern Britain.", answer: "Hadrian's" },
      { format: 'contrast', prompt: 'Which Roman emperor consolidated borders and built a wall in Britain?', answer: 'Hadrian', distractors: ['Trajan', 'Nero', 'Caligula'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'marcus-aurelius', relation: 'influenced_by' },
    ],
  },
  {
    id: 'marcus-aurelius',
    name: 'Marcus Aurelius',
    domain: 'history',
    approxYear: 161,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman emperor from 161 to 180 CE and a Stoic philosopher, Marcus Aurelius wrote his private reflections in Greek â€” now known as the Meditations â€” while campaigning on the Danube frontier. He is counted among the "Five Good Emperors" whose rule Gibbon called the period when humanity was most happy. His death in 180 CE is often marked as the end of the Pax Romana.',
    wikipedia: 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Marcus Aurelius wrote personal philosophical reflections known as the ____.', answer: 'Meditations' },
      { format: 'contrast', prompt: 'Which Roman emperor was also a Stoic philosopher?', answer: 'Marcus Aurelius', distractors: ['Julius Caesar', 'Nero', 'Diocletian'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'pax-romana', relation: 'part_of' },
      { to: 'hadrian-emperor', relation: 'successor_of' },
    ],
  },
  {
    id: 'nero-emperor',
    name: 'Nero',
    domain: 'history',
    approxYear: 54,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman emperor from 54 to 68 CE, notorious for his cruelty, extravagance, and the persecution of Christians after the Great Fire of Rome in 64 CE, which he was accused of starting. He executed his own mother Agrippina and his first wife, and his reign ended when the Senate declared him a public enemy and he took his own life. Ancient sources portray him as the archetypal tyrant emperor.',
    wikipedia: 'https://en.wikipedia.org/wiki/Nero',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Nero blamed ____ for the Great Fire of Rome in 64 CE.', answer: 'Christians' },
      { format: 'contrast', prompt: 'Which emperor was declared a public enemy by the Roman Senate?', answer: 'Nero', distractors: ['Caligula', 'Domitian', 'Commodus'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'roman-persecution-christians', relation: 'caused' },
    ],
  },
  {
    id: 'vespasian-emperor',
    name: 'Vespasian',
    domain: 'history',
    approxYear: 69,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman emperor from 69 to 79 CE, the founder of the Flavian dynasty, who restored stability after the chaotic Year of the Four Emperors. Vespasian is best remembered for beginning construction of the Colosseum in Rome around 70 CE and for his quip â€” upon introducing a tax on urine â€” that "money does not smell." He also crushed the Jewish revolt and oversaw the destruction of the Second Temple in Jerusalem.',
    wikipedia: 'https://en.wikipedia.org/wiki/Vespasian',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Vespasian began construction of the ____ around 70 CE.', answer: 'Colosseum' },
      { format: 'contrast', prompt: 'Which Roman emperor founded the Flavian dynasty?', answer: 'Vespasian', distractors: ['Augustus', 'Tiberius', 'Trajan'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'colosseum', relation: 'caused' },
    ],
  },
  {
    id: 'diocletian-emperor',
    name: 'Diocletian',
    domain: 'history',
    approxYear: 284,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman emperor from 284 to 305 CE who stabilised the empire after the chaotic third-century crisis by creating the Tetrarchy â€” a system of four co-rulers dividing administrative duties. He also launched the last and most severe persecution of Christians in 303 CE, known as the Great Persecution. Unusually for a Roman emperor, he voluntarily abdicated in 305 CE and retired to grow cabbages in his palace at Split (modern Croatia).',
    wikipedia: 'https://en.wikipedia.org/wiki/Diocletian',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Diocletian stabilised the empire by creating the ____, a system of four co-rulers.', answer: 'Tetrarchy' },
      { format: 'contrast', prompt: 'Which Roman emperor voluntarily abdicated and retired to his palace in Split?', answer: 'Diocletian', distractors: ['Augustus', 'Constantine I', 'Nero'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'third-century-crisis', relation: 'successor_of' },
      { to: 'constantine-i', relation: 'influenced_by' },
    ],
  },
  {
    id: 'roman-engineering',
    name: 'Roman Engineering',
    domain: 'science',
    approxYear: 100,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Romans built an empire-wide infrastructure of roads, aqueducts, and concrete structures that shaped Europe for two millennia. At its height the road network stretched over 400,000 km, and aqueducts carried fresh water to cities at a rate that London only matched in the 19th century. Roman concrete (opus caementicium), using volcanic ash, has proved so durable that structures like the Pantheon still stand intact.',
    wikipedia: 'https://en.wikipedia.org/wiki/Roman_engineering',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Roman ____ carried fresh water from mountains into cities across the empire.', answer: 'aqueducts' },
      { format: 'contrast', prompt: 'Which volcanic material made Roman concrete exceptionally durable?', answer: 'Volcanic ash (pozzolana)', distractors: ['Limestone', 'Sandstone', 'Gypsum'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
    ],
  },
  {
    id: 'roman-law',
    name: 'Roman Law',
    domain: 'history',
    approxYear: -450,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The legal tradition that began with the Twelve Tables (c. 450 BCE), Rome\'s first written law code, and evolved into a sophisticated system of civil, criminal, and public law spanning a millennium. Justinian I codified it in the Corpus Juris Civilis in 529â€“534 CE, which became the foundation of most European legal systems. Concepts like innocent until proven guilty, legal personhood, and contract law derive from this tradition.',
    wikipedia: 'https://en.wikipedia.org/wiki/Roman_law',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Rome's first written law code, inscribed on bronze tablets around 450 BCE, was called the Twelve ____.", answer: 'Tables' },
      { format: 'contrast', prompt: 'Which emperor later codified Roman law into the Corpus Juris Civilis?', answer: 'Justinian I', distractors: ['Augustus', 'Hadrian', 'Constantine I'] },
    ],
    edges: [
      { to: 'roman-republic', relation: 'part_of' },
      { to: 'justinian-i', relation: 'influenced_by' },
      { to: 'justinian-code', relation: 'caused' },
    ],
  },
  {
    id: 'roman-gladiators',
    name: 'Roman Gladiators and Arena Culture',
    domain: 'culture',
    approxYear: 100,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Gladiatorial combat staged in amphitheatres was the most popular public spectacle in ancient Rome, combining sport, religion, and political theatre. Gladiators were usually enslaved people, prisoners of war, or convicted criminals who trained rigorously and fought in specialised styles, with the murmillo and retiarius (net-fighter) among the most famous. The thumbs-up or thumbs-down gesture deciding a fallen fighter\'s fate is largely a 19th-century myth â€” ancient sources suggest the crowd waved their handkerchiefs instead.',
    wikipedia: 'https://en.wikipedia.org/wiki/Gladiator',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The gladiator known as the "net-fighter" was called a ____.', answer: 'retiarius' },
      { format: 'contrast', prompt: 'Where were Roman gladiatorial games primarily held?', answer: 'Amphitheatres', distractors: ['Circuses', 'Temples', 'Basilicas'] },
    ],
    edges: [
      { to: 'colosseum', relation: 'part_of' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'spartacus-revolt', relation: 'influenced_by' },
    ],
  },
  {
    id: 'constantine-i',
    name: 'Constantine I',
    domain: 'history',
    approxYear: 306,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman emperor from 306 to 337 CE, Constantine was the first emperor to convert to Christianity and issued the Edict of Milan in 313 CE granting religious tolerance throughout the empire. He convened the Council of Nicaea in 325 CE to unify Christian doctrine and founded Constantinople (modern Istanbul) as the new eastern capital of the empire in 330 CE. His conversion permanently altered the trajectory of Western civilisation.',
    wikipedia: 'https://en.wikipedia.org/wiki/Constantine_the_Great',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Constantine I founded ____ as the new eastern capital of the Roman Empire in 330 CE.', answer: 'Constantinople' },
      { format: 'contrast', prompt: 'Which Roman emperor issued the Edict of Milan granting religious tolerance?', answer: 'Constantine I', distractors: ['Theodosius I', 'Diocletian', 'Augustus'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'edict-of-milan', relation: 'caused' },
      { to: 'council-of-nicaea', relation: 'caused' },
      { to: 'byzantine-empire', relation: 'caused' },
      { to: 'diocletian-emperor', relation: 'successor_of' },
    ],
  },
  {
    id: 'edict-of-milan',
    name: 'Edict of Milan',
    domain: 'history',
    approxYear: 313,
    eras: ['classical'],
    lat: 45.5,
    lng: 9.2,
    summary:
      'A proclamation issued in 313 CE by emperors Constantine I and Licinius granting religious tolerance throughout the Roman Empire, effectively ending state persecution of Christians. It did not make Christianity the official religion â€” it simply ensured all citizens could worship freely. This single document shifted the empire\'s relationship with Christianity from persecution to patronage.',
    wikipedia: 'https://en.wikipedia.org/wiki/Edict_of_Milan',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Edict of Milan (313 CE) granted ____ tolerance throughout the Roman Empire.', answer: 'religious' },
      { format: 'contrast', prompt: 'Who issued the Edict of Milan in 313 CE?', answer: 'Constantine I and Licinius', distractors: ['Augustus and Agrippa', 'Diocletian', 'Theodosius I'] },
    ],
    edges: [
      { to: 'constantine-i', relation: 'influenced_by' },
      { to: 'roman-persecution-christians', relation: 'successor_of' },
      { to: 'christianity-core', relation: 'influenced_by' },
    ],
  },
  {
    id: 'council-of-nicaea',
    name: 'Council of Nicaea',
    domain: 'history',
    approxYear: 325,
    eras: ['classical'],
    lat: 40.4,
    lng: 29.7,
    summary:
      'The first ecumenical council of the Christian church, convened by Emperor Constantine I at Nicaea (modern Iznik, Turkey) in 325 CE to resolve theological disputes â€” chiefly whether Jesus was divine or created. The council condemned Arianism and produced the Nicene Creed, a statement of faith still recited by most Christians today. It established the precedent of state involvement in church doctrine that would define medieval Christendom.',
    wikipedia: 'https://en.wikipedia.org/wiki/First_Council_of_Nicaea',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Council of Nicaea (325 CE) condemned the heresy of ____, which denied the full divinity of Jesus.', answer: 'Arianism' },
      { format: 'contrast', prompt: 'What key document did the Council of Nicaea produce?', answer: 'The Nicene Creed', distractors: ['The Apostles Creed', 'The Edict of Milan', 'The Didache'] },
    ],
    edges: [
      { to: 'constantine-i', relation: 'influenced_by' },
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'nicene-creed', relation: 'caused' },
    ],
  },
  {
    id: 'third-century-crisis',
    name: 'Third-Century Crisis',
    domain: 'history',
    approxYear: 235,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'A 50-year period of near-collapse for the Roman Empire (235â€“284 CE) marked by military anarchy, plague, economic collapse, and external invasions. The empire fragmented into three competing states at one point, and over 20 emperors were proclaimed â€” most dying violently â€” in the span of five decades. Diocletian eventually restored order by creating the Tetrarchy, but Rome never fully recovered its earlier cohesion.',
    wikipedia: 'https://en.wikipedia.org/wiki/Crisis_of_the_Third_Century',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Third-Century Crisis lasted from approximately 235 to ____ CE.', answer: '284' },
      { format: 'contrast', prompt: 'Which emperor ended the Third-Century Crisis by creating the Tetrarchy?', answer: 'Diocletian', distractors: ['Constantine I', 'Aurelian', 'Marcus Aurelius'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'diocletian-emperor', relation: 'caused' },
    ],
  },
  {
    id: 'split-roman-empire',
    name: 'Split of the Roman Empire',
    domain: 'history',
    approxYear: 395,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'In 395 CE, Emperor Theodosius I died and the Roman Empire was permanently divided between his two sons: Arcadius ruled the wealthier, Greek-speaking East from Constantinople, and Honorius ruled the Latin-speaking West from Ravenna. The two halves had different trajectories â€” the West collapsed in 476 CE, while the East survived as the Byzantine Empire for another thousand years. The split formalised cultural and linguistic divisions that had been growing for over a century.',
    wikipedia: 'https://en.wikipedia.org/wiki/Division_of_the_Roman_Empire',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Roman Empire was permanently split in ____ CE after the death of Theodosius I.', answer: '395' },
      { format: 'contrast', prompt: 'Which part of the Roman Empire survived for a further thousand years after 395 CE?', answer: 'The Eastern Empire (Byzantine)', distractors: ['The Western Empire', 'The Gallic Empire', 'The Sassanid Empire'] },
    ],
    edges: [
      { to: 'theodosius-i', relation: 'influenced_by' },
      { to: 'byzantine-empire', relation: 'caused' },
      { to: 'fall-of-western-rome', relation: 'caused' },
    ],
  },
  {
    id: 'founding-of-constantinople',
    name: 'Founding of Constantinople',
    domain: 'history',
    approxYear: 330,
    eras: ['classical'],
    lat: 41.0,
    lng: 28.98,
    summary:
      'In 330 CE, Emperor Constantine I officially dedicated his new eastern capital, Nova Roma, on the site of the Greek city of Byzantium â€” it was quickly renamed Constantinople ("city of Constantine"). The city\'s position on a peninsula controlling the Bosphorus strait made it nearly impregnable, and it served as the capital of the Roman, then Byzantine, Empire for over a thousand years. It became the largest city in Europe and the Mediterranean for most of the medieval period.',
    wikipedia: 'https://en.wikipedia.org/wiki/Constantinople',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Constantinople was built on the site of the earlier Greek city of ____.', answer: 'Byzantium' },
      { format: 'contrast', prompt: 'In which year did Constantine officially dedicate Constantinople?', answer: '330 CE', distractors: ['313 CE', '395 CE', '476 CE'] },
    ],
    edges: [
      { to: 'constantine-i', relation: 'influenced_by' },
      { to: 'byzantine-empire', relation: 'caused' },
    ],
  },

  // â”€â”€ Late Antiquity & Transition â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'theodosius-i',
    name: 'Theodosius I',
    domain: 'history',
    approxYear: 379,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The last emperor to rule a unified Roman Empire, Theodosius I reigned from 379 to 395 CE and in 380 CE issued the Edict of Thessalonica, making Nicene Christianity the official state religion of the empire â€” a decisive break with Roman religious pluralism. He also banned pagan sacrifices and closed temples, effectively dismantling the old Roman religion. On his death in 395 CE the empire was divided permanently between his sons.',
    wikipedia: 'https://en.wikipedia.org/wiki/Theodosius_I',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Theodosius I made ____ Christianity the official state religion in 380 CE.', answer: 'Nicene' },
      { format: 'contrast', prompt: 'Which emperor was the last to rule a unified Roman Empire?', answer: 'Theodosius I', distractors: ['Constantine I', 'Diocletian', 'Justinian I'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'christianity-core', relation: 'influenced_by' },
      { to: 'split-roman-empire', relation: 'caused' },
    ],
  },
  {
    id: 'st-augustine',
    name: 'St Augustine of Hippo',
    domain: 'history',
    approxYear: 396,
    eras: ['classical'],
    lat: 36.9,
    lng: 7.8,
    summary:
      'A North African bishop (354â€“430 CE) whose writings shaped Christian theology more than any other Western thinker after St Paul. His Confessions is one of the earliest autobiographies in Western literature, narrating his conversion from a dissolute youth, while The City of God, written after the Visigoths sacked Rome in 410 CE, reframed history as a divine narrative. His ideas on original sin, grace, and just war remained foundational for Catholic and Protestant theology alike.',
    wikipedia: 'https://en.wikipedia.org/wiki/Augustine_of_Hippo',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'St Augustine\'s book ____ reframed history as a divine narrative, written after Rome was sacked in 410 CE.', answer: 'The City of God' },
      { format: 'contrast', prompt: 'Which early Christian work is often called the first Western autobiography?', answer: "Augustine's Confessions", distractors: ["Paul's Epistles", "Jerome's Vulgate preface", "Benedict's Rule"] },
    ],
    edges: [
      { to: 'christianity-core', relation: 'influenced_by' },
      { to: 'visigoths-sack-rome', relation: 'influenced_by' },
      { to: 'st-paul', relation: 'influenced_by' },
    ],
  },
  {
    id: 'attila-the-hun',
    name: 'Attila the Hun',
    domain: 'history',
    approxYear: 434,
    eras: ['classical'],
    lat: 47.5,
    lng: 19.0,
    summary:
      'Ruler of the Hunnic Empire from around 434 to 453 CE, Attila led devastating raids deep into both the Eastern and Western Roman Empires and was called the "Scourge of God" by his terrified contemporaries. He reached as far west as Gaul (modern France) before being turned back at the Battle of the Catalaunian Plains in 451 CE, one of the few times he was stopped. Mysteriously, he died of a nosebleed on his wedding night in 453 CE, and his empire disintegrated shortly after.',
    wikipedia: 'https://en.wikipedia.org/wiki/Attila',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Attila was defeated at the Battle of the ____ Plains in 451 CE.', answer: 'Catalaunian' },
      { format: 'contrast', prompt: 'What nickname was Attila the Hun given by his contemporaries?', answer: 'Scourge of God', distractors: ['The Barbarian King', 'Son of Mars', 'Terror of Rome'] },
    ],
    edges: [
      { to: 'fall-of-western-rome', relation: 'caused' },
      { to: 'roman-empire', relation: 'opposed' },
    ],
  },
  {
    id: 'visigoths-sack-rome',
    name: 'Visigoths Sack of Rome',
    domain: 'history',
    approxYear: 410,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'In August 410 CE, the Visigoth king Alaric I led his forces into Rome and sacked the city for three days â€” the first time Rome had been captured by a foreign enemy in 800 years. The event sent shockwaves across the empire and prompted St Augustine to write The City of God. Though the physical damage was limited, the psychological impact of Rome\'s vulnerability was immense and signalled that the Western Empire was failing.',
    wikipedia: 'https://en.wikipedia.org/wiki/Sack_of_Rome_(410)',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Visigoth king ____ led the sack of Rome in 410 CE.', answer: 'Alaric I' },
      { format: 'contrast', prompt: 'How long had it been since a foreign enemy last captured Rome before 410 CE?', answer: '800 years', distractors: ['200 years', '400 years', '600 years'] },
    ],
    edges: [
      { to: 'fall-of-western-rome', relation: 'caused' },
      { to: 'st-augustine', relation: 'influenced_by' },
      { to: 'roman-empire', relation: 'opposed' },
    ],
  },
  {
    id: 'justinian-i',
    name: 'Justinian I',
    domain: 'history',
    approxYear: 527,
    eras: ['medieval'],
    lat: 41.0,
    lng: 28.98,
    summary:
      'Byzantine emperor from 527 to 565 CE who briefly reconquered much of the former Western Roman Empire, including North Africa, Italy, and southern Spain. His lasting legacies include the Hagia Sophia, the Justinian Code (a comprehensive compilation of Roman law), and the Plague of Justinian (541 CE), which killed up to half the Byzantine population. He is revered as a saint in the Eastern Orthodox Church.',
    wikipedia: 'https://en.wikipedia.org/wiki/Justinian_I',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Justinian I commissioned the building of the ____ in Constantinople, completed in 537 CE.', answer: 'Hagia Sophia' },
      { format: 'contrast', prompt: 'Which Byzantine emperor codified Roman law into the Corpus Juris Civilis?', answer: 'Justinian I', distractors: ['Constantine I', 'Theodosius II', 'Heraclius'] },
    ],
    edges: [
      { to: 'byzantine-empire', relation: 'part_of' },
      { to: 'hagia-sophia', relation: 'caused' },
      { to: 'justinian-code', relation: 'caused' },
      { to: 'roman-law', relation: 'influenced_by' },
    ],
  },
  {
    id: 'hagia-sophia',
    name: 'Hagia Sophia',
    domain: 'culture',
    approxYear: 537,
    eras: ['medieval'],
    lat: 41.009,
    lng: 28.98,
    summary:
      'A cathedral built in Constantinople by Emperor Justinian I and completed in 537 CE, the Hagia Sophia (Greek: "Holy Wisdom") was the largest Christian church in the world for nearly a thousand years. Its revolutionary dome, 31 metres in diameter, appeared to float on a ring of windows, inspiring awe in visitors for centuries. After the Ottoman conquest in 1453, it became a mosque; it was a museum from 1934 until 2020, when it was reconverted to a mosque.',
    wikipedia: 'https://en.wikipedia.org/wiki/Hagia_Sophia',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Hagia Sophia served as the world\'s largest ____ for nearly a thousand years after 537 CE.', answer: 'Christian church' },
      { format: 'contrast', prompt: 'What does "Hagia Sophia" mean in Greek?', answer: 'Holy Wisdom', distractors: ['Holy City', 'Sacred Throne', 'Divine Light'] },
    ],
    edges: [
      { to: 'justinian-i', relation: 'influenced_by' },
      { to: 'byzantine-empire', relation: 'part_of' },
    ],
  },
  {
    id: 'justinian-code',
    name: 'Justinian Code',
    domain: 'history',
    approxYear: 529,
    eras: ['medieval'],
    lat: 41.0,
    lng: 28.98,
    summary:
      'The Corpus Juris Civilis, compiled under Emperor Justinian I between 529 and 534 CE, was a comprehensive reorganisation of all Roman law from the preceding millennium. It consisted of four parts â€” the Codex, Digest, Institutes, and Novels â€” and became the foundation of civil law systems across continental Europe, Latin America, and beyond. Napoleon\'s Civil Code and many modern European constitutions trace their legal DNA directly to this compilation.',
    wikipedia: 'https://en.wikipedia.org/wiki/Corpus_Juris_Civilis',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "The Justinian Code's four parts included the Codex, Digest, Institutes, and ____.", answer: 'Novels' },
      { format: 'contrast', prompt: 'Which modern legal tradition most directly descends from the Justinian Code?', answer: 'Civil law (continental European)', distractors: ['Common law (English)', 'Sharia law', 'Canon law'] },
    ],
    edges: [
      { to: 'justinian-i', relation: 'influenced_by' },
      { to: 'roman-law', relation: 'successor_of' },
    ],
  },
  {
    id: 'silk-road-byzantium',
    name: 'Silk Road under Byzantium',
    domain: 'history',
    approxYear: 500,
    eras: ['medieval'],
    lat: 41.0,
    lng: 28.98,
    summary:
      'The Byzantine Empire controlled key western nodes of the Silk Road trading network, channelling luxury goods â€” silk, spices, glassware, and gold â€” between Asia and Europe. Byzantine merchants and diplomats maintained trade routes stretching to China and India, and Constantinople\'s markets were the envy of medieval Europe. Justinian I even smuggled silkworm eggs out of China around 552 CE, breaking the Chinese monopoly on silk production.',
    wikipedia: 'https://en.wikipedia.org/wiki/Silk_Road',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Justinian I broke the Chinese silk monopoly by smuggling ____ eggs out of China around 552 CE.', answer: 'silkworm' },
      { format: 'contrast', prompt: 'Which city served as the main western terminus of the Silk Road under Byzantine control?', answer: 'Constantinople', distractors: ['Alexandria', 'Rome', 'Antioch'] },
    ],
    edges: [
      { to: 'byzantine-empire', relation: 'part_of' },
      { to: 'justinian-i', relation: 'influenced_by' },
    ],
  },
  {
    id: 'sassanid-empire',
    name: 'Sassanid Persian Empire',
    domain: 'history',
    approxYear: 224,
    eras: ['classical'],
    lat: 32.0,
    lng: 53.0,
    summary:
      'The last pre-Islamic Persian empire, ruling from 224 to 651 CE, the Sassanids were the Byzantine Empire\'s great eastern rival and fought a series of devastating wars that exhausted both powers. At its height, the empire stretched from modern Iraq to Pakistan, with Zoroastrianism as the state religion. The Arab Muslim conquests swept away the Sassanid state in 651 CE, leaving a Persian cultural legacy that deeply shaped Islamic civilisation.',
    wikipedia: 'https://en.wikipedia.org/wiki/Sasanian_Empire',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Sassanid Empire\'s state religion was ____.', answer: 'Zoroastrianism' },
      { format: 'contrast', prompt: 'Which empire was the main rival to the Byzantines before the Arab conquests?', answer: 'The Sassanid Persian Empire', distractors: ['The Hunnic Empire', 'The Parthian Empire', 'The Gupta Empire'] },
    ],
    edges: [
      { to: 'byzantine-empire', relation: 'opposed' },
      { to: 'islam-core', relation: 'influenced_by' },
    ],
  },

  // â”€â”€ Hellenistic World â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'ptolemaic-egypt',
    name: 'Ptolemaic Egypt',
    domain: 'history',
    approxYear: -305,
    eras: ['classical'],
    lat: 30.0,
    lng: 31.2,
    summary:
      'The kingdom founded by Ptolemy I, one of Alexander the Great\'s generals, after Alexander\'s death in 323 BCE, lasting until Cleopatra VII\'s death in 30 BCE. The Ptolemies ruled as pharaohs while speaking Greek, creating a blended Greco-Egyptian culture that produced the Library of Alexandria and made Alexandria the intellectual capital of the ancient world. Egypt then became the breadbasket of the Roman Empire.',
    wikipedia: 'https://en.wikipedia.org/wiki/Ptolemaic_Kingdom',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Ptolemaic Egypt was founded by Ptolemy I, a general of ____.', answer: 'Alexander the Great' },
      { format: 'contrast', prompt: 'Which Ptolemaic ruler was the last pharaoh of Egypt?', answer: 'Cleopatra VII', distractors: ['Ptolemy XII', 'Cleopatra VI', 'Berenice IV'] },
    ],
    edges: [
      { to: 'alexander-the-great', relation: 'successor_of' },
      { to: 'cleopatra-vii', relation: 'caused' },
      { to: 'library-of-alexandria', relation: 'caused' },
      { to: 'roman-empire', relation: 'influenced_by' },
    ],
  },
  {
    id: 'cleopatra-vii',
    name: 'Cleopatra VII',
    domain: 'history',
    approxYear: -51,
    eras: ['classical'],
    lat: 31.2,
    lng: 29.9,
    summary:
      'The last active ruler of the Ptolemaic Kingdom of Egypt (reigning 51â€“30 BCE), Cleopatra VII was the first in her dynasty to learn Egyptian, and she spoke nine languages. Her political alliances with Julius Caesar and later Mark Antony kept Egypt independent against Roman power; after Antony\'s defeat at Actium, she took her own life rather than be paraded in Rome\'s triumph. Her death ended three millennia of pharaonic rule in Egypt.',
    wikipedia: 'https://en.wikipedia.org/wiki/Cleopatra',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Cleopatra VII formed political alliances with Julius Caesar and later ____.', answer: 'Mark Antony' },
      { format: 'contrast', prompt: 'What made Cleopatra VII unusual among the Ptolemaic rulers?', answer: 'She was the first to learn Egyptian', distractors: ['She was the youngest ruler', 'She converted to Roman religion', 'She led armies in battle herself'] },
    ],
    edges: [
      { to: 'ptolemaic-egypt', relation: 'part_of' },
      { to: 'julius-caesar', relation: 'influenced_by' },
      { to: 'mark-antony', relation: 'influenced_by' },
      { to: 'augustus-caesar', relation: 'opposed' },
      { to: 'cleopatra-and-caesar', relation: 'part_of' },
    ],
  },
  {
    id: 'library-of-alexandria',
    name: 'Library of Alexandria',
    domain: 'culture',
    approxYear: -285,
    eras: ['classical'],
    lat: 31.2,
    lng: 29.9,
    summary:
      'The greatest library of the ancient world, established in Alexandria, Egypt, under the Ptolemaic kings in the 3rd century BCE, reportedly holding up to 700,000 scrolls. Scholars there made foundational advances in mathematics, astronomy, medicine, and linguistics â€” Euclid wrote his Elements here, and Eratosthenes calculated the circumference of the Earth. It did not burn in a single dramatic fire; it declined gradually over centuries of neglect and reduced funding.',
    wikipedia: 'https://en.wikipedia.org/wiki/Library_of_Alexandria',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The mathematician ____ wrote his Elements at the Library of Alexandria.', answer: 'Euclid' },
      { format: 'contrast', prompt: 'How did the Library of Alexandria most likely end?', answer: 'Gradual decline over centuries', distractors: ['Burned down in one fire', 'Destroyed by an earthquake', 'Deliberately demolished by the Romans'] },
    ],
    edges: [
      { to: 'ptolemaic-egypt', relation: 'part_of' },
      { to: 'euclid', relation: 'influenced_by' },
      { to: 'alexander-the-great', relation: 'influenced_by' },
    ],
  },
  {
    id: 'seleucid-empire',
    name: 'Seleucid Empire',
    domain: 'history',
    approxYear: -312,
    eras: ['classical'],
    lat: 36.2,
    lng: 37.2,
    summary:
      'The largest of Alexander the Great\'s successor states, the Seleucid Empire at its peak (c. 300 BCE) controlled territory stretching from modern Turkey and Syria to Afghanistan and Pakistan. Founded by Seleucus I Nicator, it spread Hellenistic culture across the Near East, building Greek-style cities and using Greek as the administrative language. It gradually fragmented under Parthian pressure from the east and Roman pressure from the west, collapsing in 63 BCE when Rome absorbed its last remnant.',
    wikipedia: 'https://en.wikipedia.org/wiki/Seleucid_Empire',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Seleucid Empire was founded by ____, one of Alexander the Great\'s generals.', answer: 'Seleucus I Nicator' },
      { format: 'contrast', prompt: 'When did Rome finally absorb the last remnant of the Seleucid Empire?', answer: '63 BCE', distractors: ['146 BCE', '31 BCE', '100 CE'] },
    ],
    edges: [
      { to: 'alexander-the-great', relation: 'successor_of' },
      { to: 'roman-republic', relation: 'opposed' },
      { to: 'spread-of-greek-language', relation: 'caused' },
    ],
  },
  {
    id: 'spread-of-greek-language',
    name: 'Spread of Greek Language (Koine)',
    domain: 'culture',
    approxYear: -300,
    eras: ['classical'],
    lat: 37.0,
    lng: 35.0,
    summary:
      'After Alexander the Great\'s conquests, a simplified, common dialect of Greek called Koine ("common") became the lingua franca of the eastern Mediterranean world from Egypt to Afghanistan. The New Testament was written in Koine Greek, making it accessible to millions across the Roman Empire, and Koine is the ancestor of modern Greek. Its spread was arguably Alexander\'s most enduring legacy, cementing Hellenistic culture across diverse societies.',
    wikipedia: 'https://en.wikipedia.org/wiki/Koine_Greek',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The New Testament was written in ____ Greek, the common dialect of the eastern Mediterranean.', answer: 'Koine' },
      { format: 'contrast', prompt: 'Which conqueror\'s campaigns caused the spread of Koine Greek across the Near East?', answer: 'Alexander the Great', distractors: ['Julius Caesar', 'Augustus Caesar', 'Ptolemy I'] },
    ],
    edges: [
      { to: 'alexander-the-great', relation: 'influenced_by' },
      { to: 'new-testament', relation: 'influenced_by' },
      { to: 'seleucid-empire', relation: 'part_of' },
      { to: 'ptolemaic-egypt', relation: 'part_of' },
    ],
  },

  // â”€â”€ Early Christianity â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'st-paul',
    name: 'St Paul and the Apostolic Missions',
    domain: 'history',
    approxYear: 50,
    eras: ['classical'],
    lat: 37.9,
    lng: 23.7,
    summary:
      'A Pharisaic Jew from Tarsus who, after a dramatic conversion experience on the road to Damascus, became Christianity\'s most prolific missionary, travelling across the Roman Empire to found communities in Greece, Asia Minor, and possibly Rome. His letters (the Epistles) constitute roughly a third of the New Testament and provided the theological framework â€” justification by faith, the universality of salvation â€” that shaped all later Christian thought. He was executed in Rome around 64â€“68 CE.',
    wikipedia: 'https://en.wikipedia.org/wiki/Paul_the_Apostle',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'St Paul converted to Christianity after a vision on the road to ____.', answer: 'Damascus' },
      { format: 'contrast', prompt: "Which of St Paul's contributions most shaped Western Christian theology?", answer: 'His Epistles and doctrine of justification by faith', distractors: ["His biography of Jesus's life", 'His translation of the Old Testament', 'His foundation of the papacy'] },
    ],
    edges: [
      { to: 'christianity-core', relation: 'caused' },
      { to: 'new-testament', relation: 'caused' },
      { to: 'roman-empire', relation: 'part_of' },
    ],
  },
  {
    id: 'new-testament',
    name: 'New Testament Composition',
    domain: 'history',
    approxYear: 70,
    eras: ['classical'],
    lat: 33.0,
    lng: 36.0,
    summary:
      'The 27 books of the New Testament were written in Koine Greek between roughly 50 and 120 CE, beginning with Paul\'s Epistles and culminating with the Gospel of John and the Book of Revelation. The four Gospels (Matthew, Mark, Luke, John) recount Jesus\'s life and teachings; the earliest, Mark, is believed to date to around 70 CE. The canon was not formally settled until the late 4th century, with the Council of Carthage (397 CE) listing the books recognised today.',
    wikipedia: 'https://en.wikipedia.org/wiki/New_Testament',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The earliest of the four Gospels, written around 70 CE, is the Gospel of ____.', answer: 'Mark' },
      { format: 'contrast', prompt: 'In which language was the New Testament originally written?', answer: 'Koine Greek', distractors: ['Aramaic', 'Latin', 'Hebrew'] },
    ],
    edges: [
      { to: 'st-paul', relation: 'influenced_by' },
      { to: 'spread-of-greek-language', relation: 'influenced_by' },
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'st-jerome-vulgate', relation: 'influenced_by' },
    ],
  },
  {
    id: 'roman-persecution-christians',
    name: 'Roman Persecution of Christians',
    domain: 'history',
    approxYear: 64,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Christians faced intermittent persecution across the Roman Empire from Nero\'s scapegoating after the 64 CE fire in Rome through Diocletian\'s Great Persecution of 303â€“311 CE. The persecution was rarely empire-wide or systematic; it often depended on local governors and was triggered by Christians refusing to sacrifice to Roman gods. The willingness of martyrs to die for their faith paradoxically accelerated the religion\'s spread, prompting the early Christian saying "the blood of the martyrs is the seed of the church."',
    wikipedia: 'https://en.wikipedia.org/wiki/Persecution_of_Christians_in_the_Roman_Empire',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The last and most severe Roman persecution of Christians was ordered by Emperor ____ in 303 CE.', answer: 'Diocletian' },
      { format: 'contrast', prompt: 'Which emperor first blamed Christians for a disaster, triggering persecution?', answer: 'Nero', distractors: ['Trajan', 'Domitian', 'Decius'] },
    ],
    edges: [
      { to: 'nero-emperor', relation: 'influenced_by' },
      { to: 'diocletian-emperor', relation: 'influenced_by' },
      { to: 'edict-of-milan', relation: 'caused' },
      { to: 'christianity-core', relation: 'part_of' },
    ],
  },
  {
    id: 'nicene-creed',
    name: 'Nicene Creed',
    domain: 'history',
    approxYear: 325,
    eras: ['classical'],
    lat: 40.4,
    lng: 29.7,
    summary:
      'A statement of Christian belief first formulated at the Council of Nicaea in 325 CE and refined at the Council of Constantinople in 381 CE, asserting that Jesus is "of one substance with the Father" â€” a direct rejection of Arianism. It remains the most widely used creed in Christianity, recited weekly by Roman Catholics, Eastern Orthodox, and many Protestant denominations. The single Latin word "Filioque" â€” affirming the Spirit proceeds from both Father and Son â€” caused the Great Schism of 1054 between Rome and Constantinople.',
    wikipedia: 'https://en.wikipedia.org/wiki/Nicene_Creed',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Nicene Creed states that Jesus is "of one ____ with the Father", rejecting Arianism.', answer: 'substance' },
      { format: 'contrast', prompt: 'Which single Latin word in the Nicene Creed caused the Great Schism of 1054?', answer: 'Filioque', distractors: ['Homoousios', 'Sanctus', 'Credo'] },
    ],
    edges: [
      { to: 'council-of-nicaea', relation: 'influenced_by' },
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'byzantine-empire', relation: 'influenced_by' },
    ],
  },
  {
    id: 'early-monasticism',
    name: 'Early Monasticism and Benedict of Nursia',
    domain: 'history',
    approxYear: 529,
    eras: ['medieval'],
    lat: 41.6,
    lng: 13.8,
    summary:
      'Christian monasticism began in the Egyptian desert in the 3rd century CE with hermits like Anthony the Great, but Benedict of Nursia (c. 480â€“547 CE) gave it its Western institutional form. His Rule of Saint Benedict, written around 529 CE at Monte Cassino, prescribed a balanced daily rhythm of prayer, work, and study that became the template for thousands of monasteries across medieval Europe. These monasteries preserved literacy, classical learning, and agricultural knowledge through the collapse of the Western Roman Empire.',
    wikipedia: 'https://en.wikipedia.org/wiki/Benedict_of_Nursia',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Benedict of Nursia wrote the Rule of Saint Benedict at Monte ____ around 529 CE.', answer: 'Cassino' },
      { format: 'contrast', prompt: 'Where did Christian monasticism first emerge before spreading to Europe?', answer: 'The Egyptian desert', distractors: ['Roman Judaea', 'Constantinople', 'Gaul'] },
    ],
    edges: [
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'charlemagne', relation: 'influenced_by' },
    ],
  },
  {
    id: 'st-jerome-vulgate',
    name: 'St Jerome and the Latin Vulgate Bible',
    domain: 'history',
    approxYear: 382,
    eras: ['classical'],
    lat: 31.7,
    lng: 35.2,
    summary:
      'The scholar Jerome (c. 342â€“420 CE) produced a Latin translation of the Bible from Hebrew and Greek sources on the orders of Pope Damasus I â€” a project he largely completed between 382 and 405 CE. This translation, the Vulgate ("common version"), became the standard Bible of the Western Catholic Church for over a thousand years and the basis for most medieval European scholarship. Jerome worked from Bethlehem, where he lived as a monk, and his letters and biblical commentaries are important sources for understanding early Christian intellectual life.',
    wikipedia: 'https://en.wikipedia.org/wiki/Jerome',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "St Jerome's Latin translation of the Bible is called the ____.", answer: 'Vulgate' },
      { format: 'contrast', prompt: 'For how long did the Vulgate serve as the standard Bible of the Western Church?', answer: 'Over a thousand years', distractors: ['About 300 years', 'About 500 years', 'About 200 years'] },
    ],
    edges: [
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'new-testament', relation: 'influenced_by' },
    ],
  },

  // â”€â”€ Roman Republic Final Era â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'gracchi-brothers',
    name: 'Gracchi Brothers',
    domain: 'history',
    approxYear: -133,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Tiberius and Gaius Gracchus were Roman tribunes who in 133 and 123 BCE respectively attempted sweeping land reforms to redistribute ager publicus (public land) from wealthy senators to landless citizens and veterans. Both were killed by senatorial mobs â€” Tiberius clubbed to death on the Capitoline Hill in 133 BCE â€” making them the first major victims of political violence in the Republic. Their fate foreshadowed the century of civil wars that ended the Republic, and their deaths are often cited as the beginning of the end of the Roman Republic\'s stability.',
    wikipedia: 'https://en.wikipedia.org/wiki/Gracchi',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Gracchi brothers attempted to redistribute ____ land (ager publicus) from wealthy senators to the poor.', answer: 'public' },
      { format: 'contrast', prompt: 'What happened to Tiberius Gracchus in 133 BCE?', answer: 'He was clubbed to death by a senatorial mob', distractors: ['He was exiled to Carthage', 'He was executed by crucifixion', 'He was poisoned at a banquet'] },
    ],
    edges: [
      { to: 'roman-republic', relation: 'part_of' },
      { to: 'first-triumvirate', relation: 'influenced_by' },
    ],
  },
  {
    id: 'spartacus-revolt',
    name: 'Spartacus Slave Revolt',
    domain: 'history',
    approxYear: -73,
    eras: ['classical'],
    lat: 40.9,
    lng: 14.6,
    summary:
      'The Third Servile War (73â€“71 BCE) was the largest slave rebellion in Roman history, led by the Thracian gladiator Spartacus, who escaped from a gladiatorial school in Capua and assembled an army of up to 120,000 enslaved people. The rebels defeated several Roman armies and ravaged the Italian countryside before being crushed by Crassus, and Pompey mopped up remaining forces. Six thousand captured rebels were crucified along the Appian Way from Capua to Rome.',
    wikipedia: 'https://en.wikipedia.org/wiki/Third_Servile_War',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Spartacus escaped from a gladiatorial school in ____ in 73 BCE.', answer: 'Capua' },
      { format: 'contrast', prompt: 'How many captured rebels were crucified along the Appian Way after Spartacus\'s defeat?', answer: '6,000', distractors: ['600', '60,000', '1,200'] },
    ],
    edges: [
      { to: 'roman-republic', relation: 'part_of' },
      { to: 'roman-gladiators', relation: 'influenced_by' },
      { to: 'first-triumvirate', relation: 'influenced_by' },
    ],
  },
  {
    id: 'first-triumvirate',
    name: 'First Triumvirate',
    domain: 'history',
    approxYear: -60,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'An informal power-sharing pact formed around 60 BCE between Julius Caesar, Pompey the Great, and Crassus â€” the three most powerful men in Rome â€” to dominate Roman politics. The alliance was cemented by Caesar\'s daughter Julia marrying Pompey, but Crassus\'s death at the Battle of Carrhae in 53 BCE and Julia\'s death removed the bonds holding it together. Rivalry between Caesar and Pompey then collapsed into the civil war that ended the Republic.',
    wikipedia: 'https://en.wikipedia.org/wiki/First_Triumvirate',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The First Triumvirate was an alliance between Caesar, Pompey, and ____.', answer: 'Crassus' },
      { format: 'contrast', prompt: 'What event broke the bond between Caesar and Pompey in the First Triumvirate?', answer: "Deaths of Crassus and Julia (Caesar's daughter)", distractors: ["Pompey's military defeat", "Caesar's exile", 'A Senate vote dissolving the alliance'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'part_of' },
      { to: 'roman-republic', relation: 'part_of' },
      { to: 'battle-of-pharsalus', relation: 'caused' },
    ],
  },
  {
    id: 'battle-of-pharsalus',
    name: 'Battle of Pharsalus',
    domain: 'history',
    approxYear: -48,
    eras: ['classical'],
    lat: 39.5,
    lng: 22.2,
    summary:
      'The decisive battle of the Roman civil war, fought on 9 August 48 BCE in Thessaly, Greece, where Julius Caesar defeated Pompey\'s larger army through superior tactical deployment. Pompey fled to Egypt, where he was assassinated by agents of the young pharaoh Ptolemy XIII. Caesar\'s victory left him master of the Roman world and set the stage for his relationship with Cleopatra VII.',
    wikipedia: 'https://en.wikipedia.org/wiki/Battle_of_Pharsalus',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'At the Battle of Pharsalus in 48 BCE, Caesar defeated the larger army of ____.', answer: 'Pompey' },
      { format: 'contrast', prompt: 'What happened to Pompey after his defeat at Pharsalus?', answer: 'He was assassinated in Egypt', distractors: ['He surrendered to Caesar', 'He died in battle', 'He fled to Parthia and died there'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'influenced_by' },
      { to: 'first-triumvirate', relation: 'influenced_by' },
      { to: 'cleopatra-and-caesar', relation: 'caused' },
    ],
  },
  {
    id: 'cleopatra-and-caesar',
    name: 'Cleopatra and Caesar',
    domain: 'history',
    approxYear: -48,
    eras: ['classical'],
    lat: 31.2,
    lng: 29.9,
    summary:
      'Julius Caesar arrived in Egypt in 48 BCE in pursuit of Pompey and became entangled in a dynastic war between Cleopatra VII and her brother Ptolemy XIII. Cleopatra famously had herself smuggled to Caesar in a rolled-up carpet (or linen sack) to gain a private audience, and the two became lovers; their son Caesarion was born in 47 BCE. Caesar restored Cleopatra to the Egyptian throne, cementing a strategic alliance that kept Egypt friendly to Rome until his assassination in 44 BCE.',
    wikipedia: 'https://en.wikipedia.org/wiki/Cleopatra',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Caesar and Cleopatra's son, born in 47 BCE, was named ____.", answer: 'Caesarion' },
      { format: 'contrast', prompt: 'How did Cleopatra reportedly gain her first private audience with Julius Caesar?', answer: 'Smuggled to him rolled in a carpet', distractors: ['Disguised as a Roman soldier', 'Invited to his banquet', 'Surrendered as a prisoner'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'influenced_by' },
      { to: 'cleopatra-vii', relation: 'part_of' },
      { to: 'ptolemaic-egypt', relation: 'part_of' },
    ],
  },
  {
    id: 'assassination-of-caesar',
    name: 'Assassination of Caesar (Ides of March)',
    domain: 'history',
    approxYear: -44,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'On 15 March (the Ides of March) 44 BCE, Julius Caesar was stabbed 23 times by a group of senators led by Brutus and Cassius in the Theatre of Pompey in Rome. The conspirators believed they were saving the Republic from one-man rule; instead, Caesar\'s death triggered 17 more years of civil wars that destroyed the very Republic they sought to protect. Caesar\'s adopted heir Octavian (later Augustus) used the murder as political fuel to outmanoeuvre all rivals.',
    wikipedia: 'https://en.wikipedia.org/wiki/Assassination_of_Julius_Caesar',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Julius Caesar was assassinated on the Ides of March â€” the ____ of March â€” in 44 BCE.', answer: '15th' },
      { format: 'contrast', prompt: 'How many times was Caesar stabbed on the Ides of March?', answer: '23', distractors: ['7', '33', '13'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'caused' },
      { to: 'second-triumvirate', relation: 'caused' },
      { to: 'augustus-caesar', relation: 'influenced_by' },
      { to: 'roman-republic', relation: 'part_of' },
    ],
  },
  {
    id: 'second-triumvirate',
    name: 'Second Triumvirate',
    domain: 'history',
    approxYear: -43,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Formed in 43 BCE, the Second Triumvirate was an official five-year executive commission legalising the joint rule of Octavian (Caesar\'s heir), Mark Antony (Caesar\'s general), and Lepidus. Unlike the first, this was a formal legal arrangement giving the three men dictatorial powers; they used them to conduct brutal proscriptions, executing hundreds of senators including Cicero. The alliance fractured as Octavian and Antony competed for supreme power, ending at the Battle of Actium in 31 BCE.',
    wikipedia: 'https://en.wikipedia.org/wiki/Second_Triumvirate',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Second Triumvirate was formed by Octavian, Mark Antony, and ____.', answer: 'Lepidus' },
      { format: 'contrast', prompt: 'How did the Second Triumvirate differ from the First?', answer: 'It was a formal legal commission, not an informal alliance', distractors: ['It had four members instead of three', 'It was formed voluntarily by the Senate', 'It excluded Caesar\'s heir'] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'influenced_by' },
      { to: 'augustus-caesar', relation: 'caused' },
      { to: 'mark-antony', relation: 'part_of' },
      { to: 'assassination-of-caesar', relation: 'influenced_by' },
      { to: 'battle-of-actium', relation: 'caused' },
    ],
  },
  {
    id: 'mark-antony',
    name: 'Mark Antony',
    domain: 'history',
    approxYear: -43,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'A Roman general and politician (83â€“30 BCE) who was Caesar\'s loyal lieutenant and co-member of the Second Triumvirate before his romantic and political alliance with Cleopatra VII alienated him from Rome. His relationship with Cleopatra was portrayed in Rome as an Eastern seduction undermining Roman virtue, giving Octavian the propaganda weapon he needed to declare war. After his defeat at Actium in 31 BCE, Antony took his own life in Alexandria, followed shortly by Cleopatra.',
    wikipedia: 'https://en.wikipedia.org/wiki/Mark_Antony',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'After his defeat at Actium in 31 BCE, Mark Antony took his own life in ____.', answer: 'Alexandria' },
      { format: 'contrast', prompt: 'What gave Octavian propaganda to declare war on Mark Antony?', answer: "Antony's alliance and relationship with Cleopatra", distractors: ["Antony's invasion of Italy", "Antony's betrayal of Caesar's will", "Antony's alliance with Parthia"] },
    ],
    edges: [
      { to: 'julius-caesar', relation: 'influenced_by' },
      { to: 'cleopatra-vii', relation: 'influenced_by' },
      { to: 'second-triumvirate', relation: 'part_of' },
      { to: 'augustus-caesar', relation: 'opposed' },
      { to: 'battle-of-actium', relation: 'caused' },
    ],
  },
  {
    id: 'battle-of-actium',
    name: 'Battle of Actium',
    domain: 'history',
    approxYear: -31,
    eras: ['classical'],
    lat: 38.9,
    lng: 20.7,
    summary:
      'A naval battle fought on 2 September 31 BCE off the coast of northwestern Greece, in which Octavian\'s admiral Agrippa decisively defeated the combined fleet of Mark Antony and Cleopatra VII. Cleopatra fled with her treasury ships early in the battle, followed by Antony, and within a year both had committed suicide. Octavian\'s victory left him the sole ruler of the Roman world and led directly to his becoming Augustus, first emperor of Rome.',
    wikipedia: 'https://en.wikipedia.org/wiki/Battle_of_Actium',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'At the Battle of Actium in 31 BCE, Octavian\'s admiral ____ defeated the fleet of Antony and Cleopatra.', answer: 'Agrippa' },
      { format: 'contrast', prompt: 'What was the immediate consequence of Octavian\'s victory at Actium?', answer: 'He became sole ruler of the Roman world', distractors: ['He conquered Egypt as a province', 'He abolished the Senate', 'He renamed Rome "Augusta"'] },
    ],
    edges: [
      { to: 'augustus-caesar', relation: 'caused' },
      { to: 'mark-antony', relation: 'opposed' },
      { to: 'cleopatra-vii', relation: 'influenced_by' },
      { to: 'second-triumvirate', relation: 'influenced_by' },
      { to: 'roman-empire', relation: 'caused' },
    ],
  },

  // â”€â”€ Additional Roman Empire figures and institutions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 'trajan-emperor',
    name: 'Trajan',
    domain: 'history',
    approxYear: 98,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Roman emperor from 98 to 117 CE and the first born outside Italy (in modern Spain), Trajan expanded the empire to its greatest territorial extent through his conquest of Dacia (modern Romania) and campaigns against Parthia. Trajan's Column, still standing in Rome, commemorates the Dacian wars with a 200-metre spiral frieze of carved reliefs. Pliny the Younger's letters to Trajan about the treatment of Christians are the earliest non-Christian Roman references to the religion.",
    wikipedia: 'https://en.wikipedia.org/wiki/Trajan',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Trajan expanded Rome to its greatest extent by conquering ____ (modern Romania).', answer: 'Dacia' },
      { format: 'contrast', prompt: 'What makes Trajan distinctive among early Roman emperors?', answer: 'He was the first born outside Italy', distractors: ['He was the first to convert to Christianity', 'He was the first to rule from Constantinople', 'He was the first to divide the empire'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'hadrian-emperor', relation: 'influenced_by' },
    ],
  },
  {
    id: 'roman-religion',
    name: 'Roman Religion and the Imperial Cult',
    domain: 'culture',
    approxYear: 27,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "The Roman state religion was polytheistic, borrowing heavily from Greek mythology and assimilating gods from conquered peoples â€” a practical tolerance that helped hold the empire together. Emperors after Augustus were deified after death (and some during their reign), and the imperial cult became a loyalty test: offering incense to the emperor's genius was a civic duty, which is why Christians and Jews faced persecution for refusing. Constantine I\'s conversion to Christianity eventually supplanted this tradition.",
    wikipedia: 'https://en.wikipedia.org/wiki/Religion_in_ancient_Rome',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Offering incense to the Roman emperor\'s ____ was a civic loyalty test that Christians refused.', answer: 'genius' },
      { format: 'contrast', prompt: 'How did Rome generally treat the religions of conquered peoples?', answer: 'With tolerance, often assimilating their gods', distractors: ['It banned all non-Roman religions', 'It required conversion to Roman gods', 'It destroyed temples of conquered peoples'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'roman-persecution-christians', relation: 'caused' },
      { to: 'constantine-i', relation: 'influenced_by' },
    ],
  },
  {
    id: 'flavian-dynasty',
    name: 'The Flavian Dynasty',
    domain: 'history',
    approxYear: 69,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Flavian dynasty (69â€“96 CE) â€” comprising Vespasian and his sons Titus and Domitian â€” followed the chaotic Year of the Four Emperors and restored stability to Rome. Titus presided over the destruction of Jerusalem and the Second Temple in 70 CE and the eruption of Vesuvius in 79 CE, earning a reputation for generosity during disasters; Domitian later became so feared that the Senate condemned his memory after his assassination in 96 CE.',
    wikipedia: 'https://en.wikipedia.org/wiki/Flavian_dynasty',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Flavian emperor ____ oversaw the destruction of Jerusalem\'s Second Temple in 70 CE.', answer: 'Titus' },
      { format: 'contrast', prompt: 'What followed the Flavian dynasty after Domitian was assassinated?', answer: 'The Nerva-Antonine dynasty (Five Good Emperors)', distractors: ['Another civil war', 'The Tetrarchy', 'The Severan dynasty'] },
    ],
    edges: [
      { to: 'vespasian-emperor', relation: 'part_of' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'colosseum', relation: 'caused' },
    ],
  },
  {
    id: 'year-of-four-emperors',
    name: 'Year of the Four Emperors',
    domain: 'history',
    approxYear: 69,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'In 69 CE, four men successively claimed the title of Roman emperor â€” Galba, Otho, Vitellius, and finally Vespasian â€” exposing the dangerous secret that an emperor could be made outside Rome, by armies in the provinces. The year of civil war was the first major crisis of the Principate and demonstrated that the loyalty of the legions, not the Senate, was the true source of imperial power. Vespasian\'s victory ended the Julio-Claudian dominance and founded the Flavian dynasty.',
    wikipedia: 'https://en.wikipedia.org/wiki/Year_of_the_Four_Emperors',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Year of the Four Emperors (69 CE) revealed that an emperor could be made by ____ in the provinces.', answer: 'armies' },
      { format: 'contrast', prompt: 'Who emerged as the final victor from the Year of the Four Emperors?', answer: 'Vespasian', distractors: ['Galba', 'Otho', 'Vitellius'] },
    ],
    edges: [
      { to: 'vespasian-emperor', relation: 'caused' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'nero-emperor', relation: 'influenced_by' },
    ],
  },
  {
    id: 'antonine-plague',
    name: 'Antonine Plague',
    domain: 'history',
    approxYear: 165,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'A pandemic that swept through the Roman Empire from 165 to 180 CE, killing an estimated five million people â€” possibly smallpox or measles brought back by soldiers from campaigns in the East. It struck during the reign of Marcus Aurelius and may have killed up to a third of the population in some provinces, including Marcus Aurelius\'s co-emperor Lucius Verus in 169 CE. The pandemic weakened the empire\'s tax base and military capacity, contributing to the strains of the third century.',
    wikipedia: 'https://en.wikipedia.org/wiki/Antonine_Plague',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Antonine Plague (165â€“180 CE) may have killed up to ____ million people across the Roman Empire.', answer: 'five' },
      { format: 'contrast', prompt: 'Which disease is the Antonine Plague most likely believed to have been?', answer: 'Smallpox or measles', distractors: ['Bubonic plague', 'Typhoid fever', 'Cholera'] },
    ],
    edges: [
      { to: 'marcus-aurelius', relation: 'influenced_by' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'third-century-crisis', relation: 'caused' },
    ],
  },
  {
    id: 'roman-provinces',
    name: 'Roman Provincial System',
    domain: 'history',
    approxYear: -227,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Roman Empire governed its vast territory through provinces administered by appointed governors â€” senatorial provinces under proconsuls, imperial provinces under legates directly answerable to the emperor. At its peak the empire included around 50 provinces stretching from Britain to Mesopotamia, and the provincial system spread Roman law, Latin language, and urban culture across Europe, North Africa, and the Near East. Many of today\'s European cities â€” London, Paris, Vienna, Cologne â€” began as Roman provincial settlements.',
    wikipedia: 'https://en.wikipedia.org/wiki/Roman_province',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Roman imperial provinces were governed by ____ directly answerable to the emperor.', answer: 'legates' },
      { format: 'contrast', prompt: 'Which of these cities did NOT begin as a Roman provincial settlement?', answer: 'Warsaw', distractors: ['London', 'Paris', 'Vienna'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'roman-engineering', relation: 'influenced_by' },
    ],
  },
  {
    id: 'roman-army',
    name: 'Roman Army (Legions)',
    domain: 'history',
    approxYear: -100,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Roman legions were the most professional and effective standing army in the ancient world, consisting of around 5,000 heavily armoured infantry organised into cohorts and centuries, supported by auxiliary units drawn from subject peoples. Legionaries served 25-year terms and on discharge received land or a cash bonus, making military service a path to citizenship and property for provincial men. The legions also built infrastructure â€” roads, forts, and aqueducts â€” wherever they were stationed.',
    wikipedia: 'https://en.wikipedia.org/wiki/Roman_legion',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'A Roman legion consisted of approximately ____ heavily armoured infantry.', answer: '5,000' },
      { format: 'contrast', prompt: 'How long did Roman legionaries typically serve?', answer: '25 years', distractors: ['10 years', '5 years', '40 years'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'roman-engineering', relation: 'caused' },
    ],
  },
  {
    id: 'pompeii',
    name: 'Pompeii',
    domain: 'culture',
    approxYear: 79,
    eras: ['classical'],
    lat: 40.75,
    lng: 14.49,
    summary:
      'A prosperous Roman town near Naples buried under several metres of volcanic ash and pumice when Mount Vesuvius erupted on 24 August 79 CE, killing approximately 2,000 of its residents. Rediscovered in the 18th century and extensively excavated since, Pompeii provides an unparalleled snapshot of daily Roman life â€” preserved shops, paintings, graffiti, food, and even the casts of people caught by the pyroclastic surge. It is now a UNESCO World Heritage Site and one of the most visited archaeological sites in the world.',
    wikipedia: 'https://en.wikipedia.org/wiki/Pompeii',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Pompeii was buried when Mount ____ erupted in 79 CE.', answer: 'Vesuvius' },
      { format: 'contrast', prompt: 'Why is Pompeii uniquely valuable to archaeologists?', answer: 'It preserves a snapshot of daily Roman life frozen in time', distractors: ['It contains the oldest Roman inscriptions', 'It is the only Roman city outside Italy', 'It was the largest city in the Roman Empire'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'flavian-dynasty', relation: 'influenced_by' },
      { to: 'vespasian-emperor', relation: 'influenced_by' },
    ],
  },
  {
    id: 'roman-citizenship',
    name: 'Roman Citizenship and the Edict of Caracalla',
    domain: 'history',
    approxYear: 212,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Roman citizenship â€” bringing legal protections, voting rights, and exemption from certain punishments â€” was originally restricted to Romans but gradually extended across the empire. Emperor Caracalla\'s Edict of 212 CE (Constitutio Antoniniana) granted citizenship to virtually all free inhabitants of the empire, a revolutionary act that unified the empire legally but was probably also motivated by the desire to collect more inheritance taxes. St Paul\'s famous appeal to Caesar was possible precisely because he was a Roman citizen.',
    wikipedia: 'https://en.wikipedia.org/wiki/Constitutio_Antoniniana',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Emperor Caracalla's Edict of 212 CE granted Roman citizenship to virtually all ____ inhabitants of the empire.", answer: 'free' },
      { format: 'contrast', prompt: "What is believed to have partly motivated Caracalla's grant of citizenship?", answer: 'Expanding the tax base for inheritance taxes', distractors: ['Military recruitment needs', 'Pressure from the Senate', 'Honouring a military victory'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'roman-law', relation: 'part_of' },
      { to: 'st-paul', relation: 'influenced_by' },
    ],
  },
  {
    id: 'lactantius',
    name: 'Lactantius and Early Christian Apologetics',
    domain: 'history',
    approxYear: 303,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Lactantius (c. 250â€“325 CE) was a Latin rhetorician who became one of Christianity's most eloquent defenders, writing Divine Institutes â€” the first comprehensive Latin account of the Christian religion addressed to educated pagans. He was appointed tutor to Constantine I's son Crispus, placing him at the centre of Rome's transition to Christianity. His vivid account of the deaths of the Roman emperors who persecuted Christians, De Mortibus Persecutorum, remains a primary source for historians.",
    wikipedia: 'https://en.wikipedia.org/wiki/Lactantius',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Lactantius wrote ____ Institutes, the first comprehensive Latin defence of Christianity.", answer: 'Divine' },
      { format: 'contrast', prompt: 'What role did Lactantius play at the court of Constantine I?', answer: 'Tutor to the emperor\'s son', distractors: ['Adviser on military campaigns', 'Bishop of Rome', 'Translator of the Bible'] },
    ],
    edges: [
      { to: 'constantine-i', relation: 'influenced_by' },
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'roman-persecution-christians', relation: 'influenced_by' },
    ],
  },
  {
    id: 'tetrarchy',
    name: 'The Tetrarchy',
    domain: 'history',
    approxYear: 293,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Diocletian's system of rule by four emperors simultaneously, established in 293 CE, with two senior Augusti and two junior Caesars each ruling a different quarter of the empire. The intention was to solve the succession problem and manage the empire's vast frontiers more efficiently â€” each ruler could respond quickly to crises in his zone without consulting a distant capital. It collapsed after Diocletian's abdication in 305 CE, triggering fresh civil wars that Constantine I eventually won.",
    wikipedia: 'https://en.wikipedia.org/wiki/Tetrarchy',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "The Tetrarchy comprised two senior ____ and two junior Caesars ruling different quarters of the empire.", answer: 'Augusti' },
      { format: 'contrast', prompt: 'What problem was the Tetrarchy designed to solve?', answer: 'Succession and frontier management across a vast empire', distractors: ['The budget deficit caused by the army', 'The Senate\'s resistance to imperial power', 'The spread of Christianity'] },
    ],
    edges: [
      { to: 'diocletian-emperor', relation: 'influenced_by' },
      { to: 'third-century-crisis', relation: 'successor_of' },
      { to: 'constantine-i', relation: 'caused' },
    ],
  },
  {
    id: 'odoacer',
    name: 'Odoacer and the Fall of the West',
    domain: 'history',
    approxYear: 476,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'In 476 CE, the Germanic chieftain Odoacer deposed Romulus Augustulus, the last Western Roman emperor, and sent the imperial regalia to Constantinople â€” a date conventionally marking the fall of the Western Roman Empire and the end of ancient history. Odoacer ruled Italy as king under nominal Byzantine suzerainty until 493 CE, when the Ostrogoth king Theodoric murdered him at a dinner. The year 476 is a historiographical convention; contemporaries barely noticed the event.',
    wikipedia: 'https://en.wikipedia.org/wiki/Odoacer',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Odoacer deposed the last Western Roman emperor, ____, in 476 CE.', answer: 'Romulus Augustulus' },
      { format: 'contrast', prompt: 'What did Odoacer do with the Western imperial regalia after deposing Romulus?', answer: 'Sent them to Constantinople', distractors: ['Destroyed them', 'Kept them for himself', 'Gave them to the Pope'] },
    ],
    edges: [
      { to: 'fall-of-western-rome', relation: 'caused' },
      { to: 'byzantine-empire', relation: 'influenced_by' },
    ],
  },
  {
    id: 'plague-of-justinian',
    name: 'Plague of Justinian',
    domain: 'history',
    approxYear: 541,
    eras: ['medieval'],
    lat: 41.0,
    lng: 28.98,
    summary:
      "The first pandemic of bubonic plague in recorded history, striking the Byzantine Empire in 541 CE and recurring in waves for the next two centuries. At its peak it reportedly killed 5,000 people a day in Constantinople, and modern estimates suggest 25â€“50 million deaths overall â€” possibly a quarter of the Mediterranean world's population. It devastated Justinian I's military and financial capacity just as he was attempting to reunify the Roman Empire, effectively ending that ambition.",
    wikipedia: 'https://en.wikipedia.org/wiki/Plague_of_Justinian',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "The Plague of Justinian (541 CE) was the first recorded pandemic of ____ plague.", answer: 'bubonic' },
      { format: 'contrast', prompt: "What strategic consequence did the Plague of Justinian have for Justinian I?", answer: "It ended his ambition to reunify the Roman Empire", distractors: ["It caused his conversion to Christianity", "It forced him to abandon Constantinople", "It triggered a war with Sassanid Persia"] },
    ],
    edges: [
      { to: 'justinian-i', relation: 'influenced_by' },
      { to: 'byzantine-empire', relation: 'part_of' },
      { to: 'black-death', relation: 'influenced_by' },
    ],
  },
  {
    id: 'origen-theologian',
    name: 'Origen of Alexandria',
    domain: 'history',
    approxYear: 220,
    eras: ['classical'],
    lat: 31.2,
    lng: 29.9,
    summary:
      'An early Christian scholar and theologian (c. 184â€“253 CE) based at Alexandria, Origen produced a vast body of biblical commentary, theology, and apologetics â€” his Hexapla placed six versions of the Old Testament in parallel columns for comparison. He was one of the first to systematically apply Greek philosophical methods to Christian scripture, influencing all subsequent Christian theology. He was tortured in Decius\'s persecution and died of his injuries, though he was never formally declared a martyr by the Church.',
    wikipedia: 'https://en.wikipedia.org/wiki/Origen',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "Origen's ____ placed six versions of the Old Testament in parallel columns.", answer: 'Hexapla' },
      { format: 'contrast', prompt: 'What was Origen\'s chief intellectual contribution to Christianity?', answer: 'Systematically applying Greek philosophy to Christian scripture', distractors: ['Founding the monastic movement', 'Writing the first Gospel', 'Translating the Bible into Latin'] },
    ],
    edges: [
      { to: 'library-of-alexandria', relation: 'influenced_by' },
      { to: 'christianity-core', relation: 'part_of' },
      { to: 'st-paul', relation: 'influenced_by' },
    ],
  },
  {
    id: 'julian-the-apostate',
    name: 'Julian the Apostate',
    domain: 'history',
    approxYear: 361,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "Roman emperor from 361 to 363 CE, Julian was the last non-Christian emperor and earned the epithet 'the Apostate' from Christians for his attempt to revive traditional Roman paganism after decades of Christian rule. He removed Christian privileges, restored pagan temples, and wrote philosophical works defending Neoplatonist religion â€” but died from a wound received on campaign against Persia, ending the pagan revival after less than two years. His death confirmed that Christianity's hold on the empire was permanent.",
    wikipedia: 'https://en.wikipedia.org/wiki/Julian_(emperor)',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Julian "the Apostate" was the last ____ emperor of Rome.', answer: 'non-Christian' },
      { format: 'contrast', prompt: 'Why did Julian\'s attempt to revive paganism fail?', answer: 'He died on campaign after less than two years in power', distractors: ['The Senate voted against it', 'The army refused to follow him', 'A Church council overruled him'] },
    ],
    edges: [
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'constantine-i', relation: 'opposed' },
      { to: 'theodosius-i', relation: 'influenced_by' },
    ],
  },
  {
    id: 'alaric-visigoth',
    name: 'Alaric I and the Visigoths',
    domain: 'history',
    approxYear: 395,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'Alaric I (c. 370â€“410 CE) was the first king of the Visigoths and the man who sacked Rome in 410 CE â€” the first foreign capture of the city in 800 years. A Christian himself (Arian), he had previously served in the Roman army; his sacking of Rome was partly motivated by the Western empire\'s failure to pay promised wages and grant his people land. He died suddenly shortly after the sack and was reportedly buried beneath the redirected bed of a river in southern Italy.',
    wikipedia: 'https://en.wikipedia.org/wiki/Alaric_I',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Alaric I is said to have been buried beneath the redirected bed of the ____ river in southern Italy.', answer: 'Busento' },
      { format: 'contrast', prompt: 'What was Alaric\'s religious identity?', answer: 'Arian Christian', distractors: ['Pagan', 'Nicene Christian', 'Zoroastrian'] },
    ],
    edges: [
      { to: 'visigoths-sack-rome', relation: 'caused' },
      { to: 'fall-of-western-rome', relation: 'caused' },
      { to: 'roman-empire', relation: 'opposed' },
    ],
  },
  {
    id: 'vandals-sack-rome',
    name: 'Vandals Sack of Rome',
    domain: 'history',
    approxYear: 455,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      "In 455 CE the Vandal king Genseric sailed from Carthage with a large fleet and sacked Rome over two weeks â€” the second major sacking of the city in the 5th century. Unlike Alaric's raiders, the Vandals systematically looted the city's treasures, including the spoils Titus had taken from the Jerusalem Temple in 70 CE. The sack gave the English language the word 'vandalism', though modern historians note the Vandals were no more destructive than most ancient armies.",
    wikipedia: 'https://en.wikipedia.org/wiki/Sack_of_Rome_(455)',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Vandal king ____ sacked Rome in 455 CE, giving the world the word "vandalism".', answer: 'Genseric' },
      { format: 'contrast', prompt: 'How did the Vandal sack of 455 CE differ from the Visigoth sack of 410 CE?', answer: 'The Vandals systematically looted over two weeks', distractors: ['The Vandals burned the city to the ground', 'The Vandals killed the emperor', 'The Vandals took the Pope hostage'] },
    ],
    edges: [
      { to: 'fall-of-western-rome', relation: 'caused' },
      { to: 'visigoths-sack-rome', relation: 'contemporary_of' },
      { to: 'roman-empire', relation: 'opposed' },
    ],
  },
  {
    id: 'boethius',
    name: 'Boethius',
    domain: 'history',
    approxYear: 524,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'A Roman senator and philosopher (c. 477â€“524 CE), Boethius served under the Ostrogoth king Theodoric before being accused of treason and executed. While awaiting execution he wrote The Consolation of Philosophy â€” a dialogue with the personified figure of Lady Philosophy on fortune, free will, and the nature of good â€” which became one of the most widely read books in medieval Europe, read by Chaucer, Dante, and Elizabeth I. He has been called "the last of the Romans and the first of the Scholastics."',
    wikipedia: 'https://en.wikipedia.org/wiki/Boethius',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'Boethius wrote The Consolation of ____ while awaiting his execution.', answer: 'Philosophy' },
      { format: 'contrast', prompt: 'Why was Boethius executed?', answer: 'He was accused of treason under the Ostrogoth king Theodoric', distractors: ['He converted to Christianity', 'He plotted against the Eastern emperor', 'He refused to pay taxes'] },
    ],
    edges: [
      { to: 'fall-of-western-rome', relation: 'influenced_by' },
      { to: 'byzantine-empire', relation: 'influenced_by' },
    ],
  },
  {
    id: 'romulus-remus',
    name: 'Foundation Myth of Rome',
    domain: 'culture',
    approxYear: -753,
    eras: ['antiquity'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Romans dated the founding of their city to 753 BCE and credited it to twin brothers Romulus and Remus, descendants of the Trojan hero Aeneas, who were suckled by a she-wolf after being abandoned. Romulus killed Remus in a dispute over the city\'s boundaries, named the city after himself, and became its first king. The myth served to connect Rome to the heroic age of Troy and to justify Roman destiny as a ruling power â€” the poet Virgil retold it in the Aeneid.',
    wikipedia: 'https://en.wikipedia.org/wiki/Romulus_and_Remus',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'According to Roman myth, the twins Romulus and Remus were suckled by a ____.', answer: 'she-wolf' },
      { format: 'contrast', prompt: 'Who wrote the epic poem connecting Rome to the Trojan hero Aeneas?', answer: 'Virgil', distractors: ['Ovid', 'Horace', 'Livy'] },
    ],
    edges: [
      { to: 'roman-republic', relation: 'caused' },
      { to: 'roman-religion', relation: 'part_of' },
    ],
  },
  {
    id: 'virgil-aeneid',
    name: 'Virgil and the Aeneid',
    domain: 'culture',
    approxYear: -19,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.5,
    summary:
      'The Aeneid, composed by the poet Virgil (70â€“19 BCE) on the commission of Augustus Caesar, narrates the wanderings of the Trojan hero Aeneas from the fall of Troy to the founding of the line that would eventually build Rome. It was deliberately modelled on Homer\'s Iliad and Odyssey, placing Roman history within the same heroic tradition as Greek epic. Virgil died before finishing it â€” he reportedly asked for it to be burned â€” but Augustus overruled him, and it became the foundational text of Roman literary culture.',
    wikipedia: 'https://en.wikipedia.org/wiki/Aeneid',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: 'The Aeneid was commissioned by ____ to give Rome an epic origin myth on par with Homer.', answer: 'Augustus Caesar' },
      { format: 'contrast', prompt: 'On which Homeric epics was the Aeneid deliberately modelled?', answer: 'The Iliad and the Odyssey', distractors: ['The Theogony and Works and Days', 'The Histories and the Symposium', 'The Republic and the Metamorphoses'] },
    ],
    edges: [
      { to: 'augustus-caesar', relation: 'influenced_by' },
      { to: 'roman-empire', relation: 'part_of' },
      { to: 'romulus-remus', relation: 'influenced_by' },
    ],
  },
  {
    id: 'pantheon-rome',
    name: 'The Pantheon',
    domain: 'culture',
    approxYear: 125,
    eras: ['classical'],
    lat: 41.9,
    lng: 12.47,
    summary:
      'A Roman temple built in its current form under Emperor Hadrian around 125 CE, the Pantheon\'s unreinforced concrete dome â€” 43.3 metres in diameter â€” was the largest in the world for over 1,300 years. The oculus at the dome\'s apex, open to the sky, is the building\'s only light source and reduces the structure\'s weight while symbolising the eye of the heavens. It has been in continuous use since antiquity, converted to a Christian church in 609 CE, and its dome directly inspired Brunelleschi\'s dome in Florence and Michelangelo\'s St Peter\'s.',
    wikipedia: 'https://en.wikipedia.org/wiki/Pantheon,_Rome',
    imageUrl: null,
    questions: [
      { format: 'cloze', prompt: "The Pantheon's unreinforced concrete dome was the world's largest for over ____ years.", answer: '1,300' },
      { format: 'contrast', prompt: "What is the Pantheon's oculus?", answer: 'An open hole at the top of the dome providing the only light', distractors: ['A gold statue in the centre', 'A mosaic depicting the gods', 'A skylight made of coloured glass'] },
    ],
    edges: [
      { to: 'hadrian-emperor', relation: 'influenced_by' },
      { to: 'roman-engineering', relation: 'part_of' },
    ],
  },
]
